import type { ConsoleData, ConsoleTabId } from "./types";

export const CONSOLE_TABS: { id: ConsoleTabId; label: string }[] = [
  { id: "strategies", label: "Strategies" },
  { id: "orders", label: "Orders" },
  { id: "rfqs", label: "RFQs" },
  { id: "fills", label: "Fills" },
  { id: "recovery", label: "Recovery" },
  { id: "receipts", label: "Receipts" },
];

export const CONSOLE: ConsoleData = {
  strategies: [
    {
      id: "STR-2041",
      marketId: "BTC-YC-24DEC26",
      side: "LONG",
      lots: 24,
      entryPrice: 588,
      initialMargin: 39_780,
      maintenanceMargin: 26_520,
      attribution: { carry: 2_180, funding: 0, fees: -240, residual: 96 },
      nextEvent: "Fixing window opens 23 Dec 2026",
      state: "ACTIVE",
    },
    {
      id: "STR-2039",
      marketId: "ETH-FC-25SEP26",
      side: "LONG",
      lots: 12,
      entryPrice: 466.5,
      initialMargin: 14_484,
      maintenanceMargin: 11_592,
      attribution: { carry: 846, funding: -1_412, fees: -188.4, residual: -34 },
      nextEvent: "Fixing window opens 25 Sep 2026, 16:00 London",
      state: "FIXING_WINDOW",
    },
    {
      id: "STR-2033",
      marketId: "EURUSD-FW-30DEC26",
      side: "LONG",
      lots: 40,
      entryPrice: 136.8,
      initialMargin: 85_280,
      maintenanceMargin: 54_080,
      attribution: { carry: 1_914, funding: 0, fees: -1_360, residual: 142 },
      nextEvent: "Scheduled roll proposal 12 Dec 2026",
      state: "ACTIVE",
    },
    {
      id: "STR-2028",
      marketId: "ARB-BS-26MAR27",
      side: "LONG",
      lots: 32,
      entryPrice: 290,
      initialMargin: 28_900,
      maintenanceMargin: 24_250,
      attribution: { carry: 512, funding: -96, fees: -150.4, residual: -18 },
      nextEvent: "Benchmark requalification review 14 Jan 2027",
      state: "ACTIVE",
    },
    {
      id: "STR-2022",
      marketId: "XAUUSD-FW-29JUN27",
      side: "SHORT",
      lots: 20,
      entryPrice: 45.2,
      initialMargin: 52_290,
      maintenanceMargin: 34_650,
      attribution: { carry: -1_268, funding: 0, fees: -725, residual: 54 },
      nextEvent: "Exit working, 20 lots unfilled at 43.10 USD",
      state: "CLOSING",
    },
    {
      id: "STR-2017",
      marketId: "BTC-YC-26MAR27",
      side: "SHORT",
      lots: 18,
      entryPrice: 631.5,
      initialMargin: 37_180,
      maintenanceMargin: 24_550,
      attribution: { carry: -1_640, funding: 0, fees: -558, residual: -46 },
      nextEvent: "Calendar roll window opens 05 Mar 2027",
      state: "ACTIVE",
    },
  ],
  orders: [
    {
      id: "ORD-77410",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      side: "ENTER",
      lots: 30,
      filledLots: 0,
      limit: "609.5 bp",
      tif: "GTC",
      route: "Direct package book",
      state: "WORKING",
      detail: "Resting inside the package book. No leg can fill on its own.",
    },
    {
      id: "ORD-77402",
      marketId: "ARB-BS-26MAR27",
      package: "ARB Basis MAR 27",
      side: "ENTER",
      lots: 50,
      filledLots: 32,
      limit: "291.0 bp",
      tif: "IOC",
      route: "Implied from component legs",
      state: "PARTIAL",
      detail: "32 lots cleared, 18 lots cancelled by immediate or cancel.",
    },
    {
      id: "ORD-77388",
      marketId: "XAUUSD-FW-29JUN27",
      package: "XAU/USD Forward JUN 27",
      side: "EXIT",
      lots: 20,
      filledLots: 0,
      limit: "43.10 USD",
      tif: "FOK",
      route: "Direct package book",
      state: "REJECTED",
      detail: "Fill or kill could not clear the full 20 lots at the limit. Nothing was executed.",
    },
  ],
  rfqs: [
    {
      id: "RFQ-5120",
      marketId: "ETH-FC-25SEP26",
      package: "ETH Funding Carry SEP 26",
      lots: 60,
      invited: 4,
      responded: 2,
      best: "436.5 bp, solver bonded",
      closesInSeconds: 42,
      state: "COLLECTING",
      disclosure: "Directed to 4 invited solvers. Size and direction are hidden from the public tape.",
    },
    {
      id: "RFQ-5108",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      lots: 25,
      invited: 5,
      responded: 5,
      best: "610.5 bp, solver bonded",
      closesInSeconds: 0,
      state: "QUOTE_SELECTED",
      disclosure: "Winning rule and the eligible quote set commitment are recorded on the receipt.",
    },
  ],
  fills: [
    {
      id: "FIL-31882",
      marketId: "ARB-BS-26MAR27",
      package: "ARB Basis MAR 27",
      side: "ENTER",
      lots: 32,
      price: "290.0 bp",
      source: "IMPLIED",
      fee: "150.40 USDC",
      at: "22 Sep 2026, 08:41 UTC",
    },
    {
      id: "FIL-31877",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      side: "ENTER",
      lots: 24,
      price: "588.0 bp",
      source: "DIRECT",
      fee: "240.00 USDC",
      at: "21 Sep 2026, 15:12 UTC",
    },
    {
      id: "FIL-31861",
      marketId: "EURUSD-FW-30DEC26",
      package: "EUR/USD Forward DEC 26",
      side: "ENTER",
      lots: 40,
      price: "136.8 pts",
      source: "SOLVER_FIRM",
      fee: "1,360.00 USDC",
      at: "19 Sep 2026, 11:04 UTC",
    },
  ],
  recovery: [
    {
      id: "REC-0416",
      marketId: "XAUUSD-FW-29JUN27",
      package: "XAU/USD Forward JUN 27",
      stage: "Submission unknown",
      state: "RECONCILING",
      detail:
        "A leg-sequenced submission was broadcast but no inclusion was observed within the reconcile window.",
      nextAction: "Re-read the authoritative protocol state before any resubmission.",
    },
  ],
  receipts: [
    {
      id: "RCP-9042",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      kind: "BEST_EXECUTION",
      commitment: "0x7c41...9ae2",
      state: "READY",
      detail: "Winning rule, eligible quote set commitment, and all-in price are ready to verify.",
    },
    {
      id: "RCP-9037",
      marketId: "ETH-FC-25SEP26",
      package: "ETH Funding Carry SEP 26",
      kind: "FIXING",
      commitment: "pending",
      state: "PENDING_FIXING",
      detail: "The fixing record opens when the 25 Sep 2026 observation window closes.",
    },
  ],
};

export const CONSOLE_COUNTS: Record<ConsoleTabId, number> = {
  strategies: CONSOLE.strategies.length,
  orders: CONSOLE.orders.length,
  rfqs: CONSOLE.rfqs.length,
  fills: CONSOLE.fills.length,
  recovery: CONSOLE.recovery.length,
  receipts: CONSOLE.receipts.length,
};
