import type { ConsoleData, ConsoleTabId } from "./types";

export const CONSOLE_TABS: { id: ConsoleTabId; label: string }[] = [
  { id: "strategies", label: "Strategies" },
  { id: "orders", label: "Orders" },
  { id: "rfqs", label: "RFQs" },
  { id: "fills", label: "Fills" },
  { id: "recovery", label: "Recovery" },
  { id: "receipts", label: "Receipts" },
];

export const CONSOLE: ConsoleData = {
  strategies: [
    {
      id: "STR-2041",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      lots: 24,
      entry: "588.0 bp",
      mark: "612.4 bp",
      unrealised: 1_464,
      collateral: "46,800.00 USDC",
      nextEvent: "Fixing window opens 23 Dec 2026",
      state: "ACTIVE",
    },
    {
      id: "STR-2039",
      marketId: "ETH-FC-25SEP26",
      package: "ETH Funding Carry SEP 26",
      lots: 12,
      entry: "466.5 bp",
      mark: "438.6 bp",
      unrealised: -669.6,
      collateral: "17,040.00 USDC",
      nextEvent: "Fixing window opens 25 Sep 2026, 16:00 London",
      state: "FIXING_WINDOW",
    },
    {
      id: "STR-2033",
      marketId: "EURUSD-FW-30DEC26",
      package: "EUR/USD Forward DEC 26",
      lots: 40,
      entry: "136.8 pts",
      mark: "142.5 pts",
      unrealised: 2_280,
      collateral: "104,000.00 USDC",
      nextEvent: "Scheduled roll proposal 12 Dec 2026",
      state: "ACTIVE",
    },
  ],
  orders: [
    {
      id: "ORD-77410",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      side: "ENTER",
      lots: 30,
      filledLots: 0,
      limit: "609.5 bp",
      tif: "GTC",
      route: "Direct package book",
      state: "WORKING",
      detail: "Resting inside the package book. No leg can fill on its own.",
    },
    {
      id: "ORD-77402",
      marketId: "ARB-BS-26MAR27",
      package: "ARB Basis MAR 27",
      side: "ENTER",
      lots: 50,
      filledLots: 32,
      limit: "291.0 bp",
      tif: "IOC",
      route: "Implied from component legs",
      state: "PARTIAL",
      detail: "32 lots cleared, 18 lots cancelled by immediate or cancel.",
    },
    {
      id: "ORD-77388",
      marketId: "XAUUSD-FW-29JUN27",
      package: "XAU/USD Forward JUN 27",
      side: "EXIT",
      lots: 20,
      filledLots: 0,
      limit: "43.10 USD",
      tif: "FOK",
      route: "Direct package book",
      state: "REJECTED",
      detail: "Fill or kill could not clear the full 20 lots at the limit. Nothing was executed.",
    },
  ],
  rfqs: [
    {
      id: "RFQ-5120",
      marketId: "ETH-FC-25SEP26",
      package: "ETH Funding Carry SEP 26",
      lots: 60,
      invited: 4,
      responded: 2,
      best: "436.5 bp, solver bonded",
      closesInSeconds: 42,
      state: "COLLECTING",
      disclosure: "Directed to 4 invited solvers. Size and direction are hidden from the public tape.",
    },
    {
      id: "RFQ-5108",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      lots: 25,
      invited: 5,
      responded: 5,
      best: "610.5 bp, solver bonded",
      closesInSeconds: 0,
      state: "QUOTE_SELECTED",
      disclosure: "Winning rule and the eligible quote set commitment are recorded on the receipt.",
    },
  ],
  fills: [
    {
      id: "FIL-31882",
      marketId: "ARB-BS-26MAR27",
      package: "ARB Basis MAR 27",
      side: "ENTER",
      lots: 32,
      price: "290.0 bp",
      source: "IMPLIED",
      fee: "150.40 USDC",
      at: "22 Sep 2026, 08:41 UTC",
    },
    {
      id: "FIL-31877",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      side: "ENTER",
      lots: 24,
      price: "588.0 bp",
      source: "DIRECT",
      fee: "240.00 USDC",
      at: "21 Sep 2026, 15:12 UTC",
    },
    {
      id: "FIL-31861",
      marketId: "EURUSD-FW-30DEC26",
      package: "EUR/USD Forward DEC 26",
      side: "ENTER",
      lots: 40,
      price: "136.8 pts",
      source: "SOLVER_FIRM",
      fee: "1,360.00 USDC",
      at: "19 Sep 2026, 11:04 UTC",
    },
  ],
  recovery: [
    {
      id: "REC-0416",
      marketId: "XAUUSD-FW-29JUN27",
      package: "XAU/USD Forward JUN 27",
      stage: "Submission unknown",
      state: "RECONCILING",
      detail:
        "A leg-sequenced submission was broadcast but no inclusion was observed within the reconcile window.",
      nextAction: "Re-read the authoritative protocol state before any resubmission.",
    },
  ],
  receipts: [
    {
      id: "RCP-9042",
      marketId: "BTC-YC-24DEC26",
      package: "BTC Yield Carry DEC 26",
      kind: "BEST_EXECUTION",
      commitment: "0x7c41...9ae2",
      state: "READY",
      detail: "Winning rule, eligible quote set commitment, and all-in price are ready to verify.",
    },
    {
      id: "RCP-9037",
      marketId: "ETH-FC-25SEP26",
      package: "ETH Funding Carry SEP 26",
      kind: "FIXING",
      commitment: "pending",
      state: "PENDING_FIXING",
      detail: "The fixing record opens when the 25 Sep 2026 observation window closes.",
    },
  ],
};

export const CONSOLE_COUNTS: Record<ConsoleTabId, number> = {
  strategies: CONSOLE.strategies.length,
  orders: CONSOLE.orders.length,
  rfqs: CONSOLE.rfqs.length,
  fills: CONSOLE.fills.length,
  recovery: CONSOLE.recovery.length,
  receipts: CONSOLE.receipts.length,
};
