import { findMarket } from "@/lib/terminal/markets";
import type { LifecycleLeg, LifecycleStrategy } from "./types";

function leg(
  marketId: string,
  legId: string,
  lifecycleRole: string,
  dependency: string,
  nextBoundaryId: string | null,
  ageSeconds: number,
): LifecycleLeg {
  const market = findMarket(marketId);
  const source = market.legs.find((candidate) => candidate.id === legId);
  if (!source) throw new Error(`Lifecycle fixture leg ${marketId}:${legId} was not found.`);

  return {
    ...source,
    lifecycleRole,
    dependency,
    nextBoundaryId,
    observation: {
      provenance: source.venueClass === "NATIVE_BOOK" ? "EXECUTABLE" : "OBSERVED",
      ageSeconds,
      source: source.venueClass === "NATIVE_BOOK" ? "Setryn package book" : "Qualified component observation",
    },
  };
}

const BTC_YIELD_CARRY = findMarket("BTC-YC-24DEC26");
const ETH_FUNDING_CARRY = findMarket("ETH-FC-25SEP26");
const EURUSD_FORWARD = findMarket("EURUSD-FW-30DEC26");

export const LIFECYCLE_STRATEGIES: LifecycleStrategy[] = [
  {
    id: "strat-btc-yield-carry-001",
    market: BTC_YIELD_CARRY,
    label: "BTC Yield Carry",
    side: "LONG",
    lots: 120,
    health: "HEALTHY",
    healthDetail: "Funding and fixing observations remain inside policy.",
    entryPrice: 603.1,
    markPrice: BTC_YIELD_CARRY.netPrice,
    closeCost: 142,
    timeToUnwindSeconds: 48,
    collateral: 30240,
    liquidationDistance: 18.4,
    maxResidual: 180,
    settlementClass: "Cash USDC at benchmark fixing",
    guarantee: "PACKAGE_ATOMIC",
    recoveryClass: "Same-domain terminal completion",
    observation: {
      provenance: "EXECUTABLE",
      ageSeconds: 4,
      source: "Setryn package book and qualified BTC fixing set",
      asOfLabel: "09:00:04 UTC",
    },
    boundaries: [
      {
        id: "btc-funding",
        kind: "FUNDING",
        label: "Funding accrual observation",
        dueLabel: "in 3h 00m",
        timing: "12:00 UTC",
        state: "UPCOMING",
        source: "Qualified component funding feed",
      },
      {
        id: "btc-roll",
        kind: "REBALANCE",
        label: "Carry roll eligibility",
        dueLabel: "in 17d",
        timing: "07 Oct 2026, 16:00 UTC",
        state: "UPCOMING",
        source: "Series lifecycle policy v1",
      },
      {
        id: "btc-fixing",
        kind: "FIXING",
        label: "Cash settlement fixing",
        dueLabel: "in 93d",
        timing: "24 Dec 2026, 16:00 UTC",
        state: "UPCOMING",
        source: BTC_YIELD_CARRY.fixingSource,
      },
    ],
    legs: [
      leg("BTC-YC-24DEC26", "btc-fwd", "Dated carry anchor", "Must remain paired with spot reference through final fixing.", "btc-fixing", 4),
      leg("BTC-YC-24DEC26", "btc-spot", "Spot hedge reference", "Close only with the forward leg unless a deliberate hedge break is authorized.", "btc-roll", 7),
      leg("BTC-YC-24DEC26", "usdc-term", "Financing leg", "Accrual is reconciled before any roll or package exit.", "btc-funding", 11),
    ],
    proposals: [
      {
        id: "btc-roll-dec-mar",
        kind: "ROLL",
        label: "Roll December carry into March series",
        actionLabel: "Prepare package roll",
        route: "STUDIO",
        summary: "Closes the December package and opens a matched March carry under one bounded roll draft.",
        quoteRequirement: "Requires fresh paired exit and entry package quotes.",
        maxCloseCost: 168,
        estimatedTimeToUnwindSeconds: 62,
        impacts: [
          { label: "Expiry", before: "24 Dec 2026", after: "26 Mar 2027", tone: "up" },
          { label: "Collateral", before: "30.2k USDC", after: "31.6k USDC" },
          { label: "Max residual", before: "180 USDC", after: "190 USDC", tone: "brand" },
          { label: "Net delta", before: "+0.02", after: "+0.02" },
        ],
        constraints: [
          { label: "December close depth", state: "SATISFIED", detail: "120 lots inside firm package depth." },
          { label: "March entry qualification", state: "SATISFIED", detail: "Target canonical series is qualified." },
          { label: "Paired quote validity", state: "REQUIRES_QUOTE", detail: "Price and route must be refreshed before authorization." },
        ],
      },
      {
        id: "btc-de-risk-40",
        kind: "DE_RISK",
        label: "Reduce package exposure by 40 lots",
        actionLabel: "Open package reduction",
        route: "TRADE",
        summary: "Closes one-third of the complete package while preserving the hedge ratio on remaining lots.",
        quoteRequirement: "Requires a 40-lot package close quote within the stated close-cost cap.",
        maxCloseCost: 58,
        estimatedTimeToUnwindSeconds: 31,
        impacts: [
          { label: "Lots", before: "120", after: "80", tone: "up" },
          { label: "Collateral", before: "30.2k USDC", after: "20.2k USDC", tone: "up" },
          { label: "Liquidation distance", before: "18.4%", after: "21.1%", tone: "up" },
          { label: "Net delta", before: "+0.02", after: "+0.01" },
        ],
        constraints: [
          { label: "Package ratio", state: "SATISFIED", detail: "All three legs reduce pro rata." },
          { label: "Firm close capacity", state: "SATISFIED", detail: "40 lots available at direct package sources." },
          { label: "Maximum close cost", state: "REQUIRES_QUOTE", detail: "Cap is enforced only in the final trade request." },
        ],
      },
      {
        id: "btc-exit-all",
        kind: "EXIT",
        label: "Exit the complete December package",
        actionLabel: "Open complete package exit",
        route: "TRADE",
        summary: "Closes every constituent leg under the selected package settlement policy.",
        quoteRequirement: "Requires a complete 120-lot exit quote.",
        maxCloseCost: 184,
        estimatedTimeToUnwindSeconds: 48,
        impacts: [
          { label: "Lots", before: "120", after: "0", tone: "up" },
          { label: "Collateral", before: "30.2k USDC", after: "0 USDC", tone: "up" },
          { label: "Max residual", before: "180 USDC", after: "0 USDC", tone: "up" },
          { label: "Lifecycle state", before: "Active", after: "Terminal" },
        ],
        constraints: [
          { label: "Full-size book capacity", state: "SATISFIED", detail: "Direct and firm solver sources cover 120 lots." },
          { label: "Final cash reconciliation", state: "REQUIRES_QUOTE", detail: "Completed only after terminal postconditions are observed." },
        ],
      },
    ],
  },
  {
    id: "strat-eth-funding-carry-002",
    market: ETH_FUNDING_CARRY,
    label: "ETH Funding Carry",
    side: "LONG",
    lots: 68,
    health: "WINDOW_OPEN",
    healthDetail: "Funding observation window closes before the next funding event.",
    entryPrice: 446.8,
    markPrice: ETH_FUNDING_CARRY.netPrice,
    closeCost: 96,
    timeToUnwindSeconds: 43,
    collateral: 14110,
    liquidationDistance: 11.7,
    maxResidual: 102,
    settlementClass: "Cash USDC at qualified fixing",
    guarantee: "SOLVER_BONDED",
    recoveryClass: "Solver-bounded recovery reserve",
    observation: {
      provenance: "EXECUTABLE",
      ageSeconds: 6,
      source: "Signed solver capacity and ETH funding observation",
      asOfLabel: "08:59:58 UTC",
    },
    boundaries: [
      {
        id: "eth-funding",
        kind: "FUNDING",
        label: "Funding observation window",
        dueLabel: "open for 21m",
        timing: "closes 09:21 UTC",
        state: "WINDOW_OPEN",
        source: "Qualified component funding feed",
      },
      {
        id: "eth-fixing",
        kind: "FIXING",
        label: "Cash settlement fixing",
        dueLabel: "today",
        timing: "25 Sep 2026, 16:00 UTC",
        state: "UPCOMING",
        source: ETH_FUNDING_CARRY.fixingSource,
      },
      {
        id: "eth-expiry",
        kind: "EXPIRY",
        label: "Series expiry",
        dueLabel: "today",
        timing: "after final fixing", 
        state: "UPCOMING",
        source: "Series lifecycle policy v1",
      },
    ],
    legs: [
      leg("ETH-FC-25SEP26", "eth-fwd", "Dated price leg", "Needs a matched funding leg until terminal settlement.", "eth-fixing", 6),
      leg("ETH-FC-25SEP26", "eth-funding", "Funding capture leg", "Observation must be final before the package claim can resolve.", "eth-funding", 8),
      leg("ETH-FC-25SEP26", "eth-fin", "USDC financing leg", "Accrual is netted with package cash settlement.", "eth-expiry", 12),
    ],
    proposals: [
      {
        id: "eth-exit-before-fixing",
        kind: "EXIT",
        label: "Exit before the final fixing",
        actionLabel: "Open protected package exit",
        route: "TRADE",
        summary: "Closes all ETH carry legs before the final fixing and releases the associated reserve after completion.",
        quoteRequirement: "Requires an unexpired firm solver or direct package quote for 68 lots.",
        maxCloseCost: 121,
        estimatedTimeToUnwindSeconds: 43,
        impacts: [
          { label: "Funding window", before: "Open", after: "No exposure", tone: "up" },
          { label: "Collateral", before: "14.1k USDC", after: "0 USDC", tone: "up" },
          { label: "Recovery reserve", before: "102 USDC", after: "0 USDC", tone: "up" },
          { label: "Settlement path", before: "Solver bounded", after: "Terminal" },
        ],
        constraints: [
          { label: "Funding observation", state: "SATISFIED", detail: "Latest observation is within the package policy window." },
          { label: "Solver capacity", state: "REQUIRES_QUOTE", detail: "Firm capacity expires with the new close quote." },
          { label: "Fixing state", state: "SATISFIED", detail: "No fixing is required after a completed package exit." },
        ],
      },
      {
        id: "eth-migrate-direct",
        kind: "MIGRATE",
        label: "Migrate to direct package settlement",
        actionLabel: "Prepare settlement migration",
        route: "STUDIO",
        summary: "Builds a replacement package on a direct settlement class and closes the existing bounded route only after both quotes qualify.",
        quoteRequirement: "Requires a qualified replacement series and two independent package quotes.",
        maxCloseCost: 138,
        estimatedTimeToUnwindSeconds: 77,
        impacts: [
          { label: "Guarantee", before: "Solver bounded", after: "Package atomic", tone: "up" },
          { label: "Recovery reserve", before: "102 USDC", after: "0 USDC", tone: "up" },
          { label: "Collateral", before: "14.1k USDC", after: "15.0k USDC", tone: "brand" },
          { label: "Net delta", before: "+0.03", after: "+0.03" },
        ],
        constraints: [
          { label: "Replacement series", state: "REQUIRES_QUOTE", detail: "Migration starts only when a canonical target is selected." },
          { label: "Bounded source exit", state: "REQUIRES_QUOTE", detail: "Existing solver quote must reserve recovery capacity." },
          { label: "Intermediate hedge", state: "SATISFIED", detail: "The compiler keeps both package commitments explicit." },
        ],
      },
    ],
  },
  {
    id: "strat-eurusd-forward-003",
    market: EURUSD_FORWARD,
    label: "EUR/USD Forward",
    side: "SHORT",
    lots: 250,
    health: "ATTENTION",
    healthDetail: "Close cost is above the preferred operating band, but inside the risk limit.",
    entryPrice: 141.9,
    markPrice: EURUSD_FORWARD.netPrice,
    closeCost: 218,
    timeToUnwindSeconds: 94,
    collateral: 23750,
    liquidationDistance: 8.9,
    maxResidual: 375,
    settlementClass: "Cash USDC NDF at WMR fixing",
    guarantee: "LEG_SEQUENCED",
    recoveryClass: "Sequenced route with bounded residual policy",
    observation: {
      provenance: "OBSERVED",
      ageSeconds: 18,
      source: "Qualified WMR and component forward observation",
      asOfLabel: "08:59:46 UTC",
    },
    boundaries: [
      {
        id: "eur-rebalance",
        kind: "REBALANCE",
        label: "Hedge-ratio review",
        dueLabel: "in 2d",
        timing: "27 Sep 2026, 16:00 UTC",
        state: "UPCOMING",
        source: "Macro forward policy v1",
      },
      {
        id: "eur-fixing",
        kind: "FIXING",
        label: "WMR NDF fixing",
        dueLabel: "in 96d",
        timing: "30 Dec 2026, 16:00 UTC",
        state: "UPCOMING",
        source: EURUSD_FORWARD.fixingSource,
      },
    ],
    legs: [
      leg("EURUSD-FW-30DEC26", "eur-fwd", "NDF anchor", "Must be settled from the same WMR fixing source as the package claim.", "eur-fixing", 18),
      leg("EURUSD-FW-30DEC26", "eur-spot", "Reference hedge", "A direct close breaks the modeled NDF hedge until a complete package rebalances.", "eur-rebalance", 19),
    ],
    proposals: [
      {
        id: "eur-rebalance-hedge",
        kind: "REBALANCE",
        label: "Rebalance the EUR/USD hedge ratio",
        actionLabel: "Prepare package rebalance",
        route: "STUDIO",
        summary: "Recompiles a two-leg ratio adjustment while retaining the same NDF fixing and settlement class.",
        quoteRequirement: "Requires a new canonical graph and fresh component depth.",
        maxCloseCost: 246,
        estimatedTimeToUnwindSeconds: 106,
        impacts: [
          { label: "Reference ratio", before: "1.00x", after: "0.96x", tone: "up" },
          { label: "Net delta", before: "-0.08", after: "-0.02", tone: "up" },
          { label: "Close cost", before: "218 USDC", after: "196 USDC", tone: "up" },
          { label: "Max residual", before: "375 USDC", after: "340 USDC", tone: "up" },
        ],
        constraints: [
          { label: "WMR fixing dependency", state: "SATISFIED", detail: "The target keeps the committed fixing source." },
          { label: "Component depth", state: "REQUIRES_QUOTE", detail: "Sequenced capacity must be re-evaluated at authorization." },
          { label: "Residual cap", state: "SATISFIED", detail: "Projected residual remains inside the account limit." },
        ],
      },
      {
        id: "eur-de-risk-100",
        kind: "DE_RISK",
        label: "Reduce package exposure by 100 lots",
        actionLabel: "Open package reduction",
        route: "TRADE",
        summary: "Reduces the complete EUR/USD package pro rata to improve close capacity and liquidation distance.",
        quoteRequirement: "Requires a bounded 100-lot close quote.",
        maxCloseCost: 96,
        estimatedTimeToUnwindSeconds: 51,
        impacts: [
          { label: "Lots", before: "250", after: "150", tone: "up" },
          { label: "Collateral", before: "23.8k USDC", after: "14.3k USDC", tone: "up" },
          { label: "Liquidation distance", before: "8.9%", after: "13.8%", tone: "up" },
          { label: "Max residual", before: "375 USDC", after: "225 USDC", tone: "up" },
        ],
        constraints: [
          { label: "Package completion", state: "REQUIRES_QUOTE", detail: "Leg-sequenced execution needs an identified residual bound." },
          { label: "Risk cap", state: "SATISFIED", detail: "The proposed reserve remains below policy maximum." },
        ],
      },
    ],
  },
];

export function lifecycleStrategy(id: string): LifecycleStrategy {
  const strategy = LIFECYCLE_STRATEGIES.find((candidate) => candidate.id === id);
  if (!strategy) throw new Error(`Lifecycle strategy ${id} was not found.`);
  return strategy;
}
