import type { GatewayExecution, GatewaySnapshot, SubmissionUpdate } from "@/lib/internal-gateway/types";

export type ActivityResultState = "COMPLETE" | "UNKNOWN" | "FAILED" | "SIMULATED";
export type ActivitySource = "RUNTIME" | "INDEXED" | "CONTRACT";

export interface ActivityStepView {
  id: SubmissionUpdate["step"];
  label: string;
  detail: string;
  transactionReference?: string;
  occurredAt: string | null;
}

export interface ActivityReceiptView {
  id: string;
  href: string;
  orderHash: string;
  fillId: string;
  transactionReference: string;
  createdAt: string;
}

export interface ActivityAttemptView {
  id: string;
  marketId: string;
  packageCode: string;
  routeLabel: string;
  orderHash: string;
  createdAt: string;
  completedAt: string | null;
  result: ActivityResultState;
  outcome: "OPENED" | "REDUCED" | "CLOSED";
  source: ActivitySource;
  evidence: GatewaySnapshot["environment"]["evidence"];
  environment: string;
  freshness: {
    label: string;
    detail: string;
  };
  lots: number;
  price: number;
  feeAmount: number;
  guarantee: string;
  receipt: ActivityReceiptView | null;
  steps: ActivityStepView[];
}

function runtimeResult(snapshot: GatewaySnapshot): ActivityResultState {
  return snapshot.environment.evidence === "DEMO" ? "SIMULATED" : "COMPLETE";
}

function toAttempt(execution: GatewayExecution, snapshot: GatewaySnapshot): ActivityAttemptView {
  const receipt = execution.result.receipt;
  const result = runtimeResult(snapshot);
  const transactionReference = receipt.transactionHash;

  return {
    id: execution.id,
    marketId: receipt.marketId,
    packageCode: receipt.packageCode,
    routeLabel: receipt.routeLabel,
    orderHash: execution.orderHash,
    createdAt: execution.createdAt,
    completedAt: receipt.createdAt,
    result,
    outcome: execution.result.outcome,
    source: "RUNTIME",
    evidence: receipt.evidence,
    environment: snapshot.environment.label,
    freshness: {
      label: result === "SIMULATED" ? "Current browser session" : "Runtime snapshot",
      detail:
        result === "SIMULATED"
          ? "Generated by the local clearing simulation. No chain transaction was broadcast."
          : "Awaiting an indexed event source for independent reconciliation.",
    },
    lots: receipt.lots,
    price: receipt.price,
    feeAmount: receipt.fees,
    guarantee: receipt.guarantee,
    receipt: {
      id: receipt.id,
      href: `/activity/receipts/${receipt.id}`,
      orderHash: receipt.orderHash,
      fillId: receipt.fillId,
      transactionReference,
      createdAt: receipt.createdAt,
    },
    steps: execution.updates.map((update, index) => ({
      id: update.step,
      label: update.label,
      detail: update.detail,
      transactionReference: update.transactionHash,
      occurredAt: index === execution.updates.length - 1 ? receipt.createdAt : null,
    })),
  };
}

export function activityAttemptsFromGateway(snapshot: GatewaySnapshot): ActivityAttemptView[] {
  return snapshot.executions
    .map((execution) => toAttempt(execution, snapshot))
    .sort((left, right) => Date.parse(right.createdAt) - Date.parse(left.createdAt));
}

