import type { OperationsSnapshot } from "@/lib/operations/types";

const capturedAt = "2026-09-25T07:40:00.000Z";

const fresh = (ageLabel: string, thresholdLabel: string, withinThreshold = true) => ({
  recordedAt: capturedAt,
  ageLabel,
  thresholdLabel,
  withinThreshold,
});

export const OPERATIONS_FIXTURE: OperationsSnapshot = {
  capturedAt,
  captureLabel: "Recorded fixture - 25 Sep 2026, 07:40 UTC",
  dependencies: [
    {
      id: "chain-reader",
      label: "Arbitrum Sepolia chain reader",
      service: "Contract state adapter",
      state: "HEALTHY",
      evidence: "RECORDED",
      freshness: fresh("18 s old", "60 s maximum"),
      checkpoint: "Block 12498114",
      detail: "Read-only contract state snapshot with deterministic block pinning.",
    },
    {
      id: "event-projector",
      label: "Protocol event projector",
      service: "Internal indexer",
      state: "HEALTHY",
      evidence: "RECORDED",
      freshness: fresh("21 s old", "90 s maximum"),
      checkpoint: "Projected through block 12498112",
      detail: "Canonical package, lifecycle, receipt, and collateral event reducers are current.",
    },
    {
      id: "pyth-verifier",
      label: "Pyth price verifier",
      service: "Oracle verification adapter",
      state: "DEGRADED",
      evidence: "RECORDED",
      freshness: fresh("51 s old", "45 s maximum", false),
      checkpoint: "BTC/USD publish time 07:39:09 UTC",
      detail: "Read path remains available. New risk admission requires a fresh verified price.",
    },
    {
      id: "solver-gateway",
      label: "Firm quote gateway",
      service: "Internal solver runtime",
      state: "HEALTHY",
      evidence: "FIXTURE",
      freshness: fresh("12 s old", "60 s maximum"),
      checkpoint: "Lease batch SQ-1948",
      detail: "Capacity reservations are represented as local fixture evidence only.",
    },
    {
      id: "keeper-scheduler",
      label: "Lifecycle keeper scheduler",
      service: "Internal operator runtime",
      state: "HEALTHY",
      evidence: "FIXTURE",
      freshness: fresh("14 s old", "60 s maximum"),
      checkpoint: "Schedule window 07:45 UTC",
      detail: "Completion remains permissionless at terminal state even if admission is stopped.",
    },
  ],
  indexerStreams: [
    {
      id: "package-events",
      label: "Package and execution events",
      state: "HEALTHY",
      headBlock: 12498114,
      projectedBlock: 12498112,
      lagBlocks: 2,
      allowedLagBlocks: 8,
      evidence: "RECORDED",
      freshness: fresh("21 s old", "90 s maximum"),
    },
    {
      id: "collateral-events",
      label: "Collateral and settlement events",
      state: "HEALTHY",
      headBlock: 12498114,
      projectedBlock: 12498113,
      lagBlocks: 1,
      allowedLagBlocks: 8,
      evidence: "RECORDED",
      freshness: fresh("18 s old", "90 s maximum"),
    },
    {
      id: "lifecycle-events",
      label: "Lifecycle and recovery events",
      state: "DEGRADED",
      headBlock: 12498114,
      projectedBlock: 12498108,
      lagBlocks: 6,
      allowedLagBlocks: 4,
      evidence: "RECORDED",
      freshness: fresh("47 s old", "60 s maximum", false),
    },
  ],
  jobQueues: [
    {
      id: "solver-quote",
      runner: "SOLVER",
      label: "Firm quote evaluation",
      state: "HEALTHY",
      queued: 4,
      leased: 2,
      delayed: 0,
      lastCompletion: "07:39:54 UTC",
      nextCheckpoint: "07:40:30 UTC",
      detail: "Routes remain simulation-only in this first-party console fixture.",
      evidence: "FIXTURE",
      freshness: fresh("12 s old", "60 s maximum"),
    },
    {
      id: "keeper-roll",
      runner: "KEEPER",
      label: "Roll and expiry preparation",
      state: "HEALTHY",
      queued: 7,
      leased: 1,
      delayed: 1,
      lastCompletion: "07:39:46 UTC",
      nextCheckpoint: "07:41:00 UTC",
      detail: "One delayed task is inside the committed execution window.",
      evidence: "FIXTURE",
      freshness: fresh("14 s old", "60 s maximum"),
    },
    {
      id: "oracle-verify",
      runner: "ORACLE_RELAY",
      label: "Oracle freshness verification",
      state: "DEGRADED",
      queued: 1,
      leased: 1,
      delayed: 1,
      lastCompletion: "07:39:09 UTC",
      nextCheckpoint: "Awaiting fresh publish",
      detail: "Stale verification blocks only price-dependent new risk, not terminal resolution.",
      evidence: "RECORDED",
      freshness: fresh("51 s old", "45 s maximum", false),
    },
  ],
  recoveryCases: [
    {
      id: "RCV-0042",
      packageCode: "BTC-YC-24DEC26",
      state: "RECOVERY_QUEUED",
      riskBoundary: "Maximum residual 0.18 BTC delta",
      residual: "0.06 BTC delta observed",
      deadline: "07:47 UTC",
      writeAuthority: "Permissionless terminal completion",
      newRiskBlocked: true,
      terminalResolutionPermitted: true,
      evidence: "FIXTURE",
      freshness: fresh("17 s old", "60 s maximum"),
      events: [
        {
          id: "RCV-0042-1",
          at: "07:38:55 UTC",
          label: "Postcondition variance recorded",
          detail: "One venue response remained unknown after the package deadline.",
          evidence: "RECORDED",
        },
        {
          id: "RCV-0042-2",
          at: "07:39:11 UTC",
          label: "Recovery bound committed",
          detail: "No additional package entry is allowed while the residual is open.",
          evidence: "RECORDED",
        },
        {
          id: "RCV-0042-3",
          at: "07:39:43 UTC",
          label: "Keeper completion queued",
          detail: "A permissionless terminal path remains available before deadline.",
          evidence: "FIXTURE",
        },
      ],
    },
    {
      id: "RCV-0039",
      packageCode: "ETH-FC-26SEP26",
      state: "RESOLUTION_READY",
      riskBoundary: "Maximum residual 12.0k USDC",
      residual: "0.0 USDC residual",
      deadline: "Resolved within committed window",
      writeAuthority: "Permissionless terminal completion",
      newRiskBlocked: false,
      terminalResolutionPermitted: true,
      evidence: "FIXTURE",
      freshness: fresh("31 s old", "60 s maximum"),
      events: [
        {
          id: "RCV-0039-1",
          at: "07:34:17 UTC",
          label: "Terminal postconditions satisfied",
          detail: "Receipt is ready for deterministic reconstruction.",
          evidence: "RECORDED",
        },
      ],
    },
  ],
  killSwitches: [
    {
      id: "package-admission",
      scope: "PACKAGE_ADMISSION",
      label: "Package admission",
      state: "ARMED",
      stops: "New package authorization and collateral reservation",
      permits: "Terminal completion, unwind, withdrawal, and evidence publication",
      changedAt: "07:31 UTC",
      actor: "risk-policy",
      evidence: "RECORDED",
    },
    {
      id: "solver-routing",
      scope: "SOLVER_ROUTING",
      label: "Solver routing",
      state: "ARMED",
      stops: "New solver route selection and quote reservation",
      permits: "Committed route reconciliation and terminal resolution",
      changedAt: "07:31 UTC",
      actor: "risk-policy",
      evidence: "RECORDED",
    },
    {
      id: "maker-quoting",
      scope: "MAKER_QUOTING",
      label: "Maker quoting",
      state: "ARMED",
      stops: "New firm quote publication",
      permits: "Quote expiry, cancelation, and committed-fill handling",
      changedAt: "07:31 UTC",
      actor: "risk-policy",
      evidence: "RECORDED",
    },
    {
      id: "lifecycle-keepers",
      scope: "LIFECYCLE_KEEPERS",
      label: "Lifecycle keepers",
      state: "ARMED",
      stops: "New discretionary lifecycle actions",
      permits: "Objective terminal completion and collateral release",
      changedAt: "07:31 UTC",
      actor: "risk-policy",
      evidence: "RECORDED",
    },
  ],
  writePolicies: [
    {
      environment: "ARBITRUM_SEPOLIA",
      label: "Arbitrum Sepolia",
      writesAllowed: true,
      policyLabel: "Testnet write intents permitted",
      detail: "Only testnet or local fixtures may be used during development. This console does not submit any write.",
      evidence: "RECORDED",
    },
    {
      environment: "ARBITRUM_ONE",
      label: "Arbitrum One",
      writesAllowed: false,
      policyLabel: "Mainnet writes hard disabled",
      detail: "No wallet, operator, keeper, solver, or deployment action may write to Arbitrum One from this development platform.",
      evidence: "RECORDED",
    },
  ],
  alerts: [
    {
      id: "ALT-194",
      severity: "WARNING",
      state: "OPEN",
      title: "Pyth verification exceeded admission threshold",
      detail: "The latest verified BTC/USD price is 6 seconds beyond the configured admission threshold.",
      source: "Oracle verification adapter",
      openedAt: "07:39:54 UTC",
      evidence: "RECORDED",
      freshness: fresh("6 s old", "45 s maximum", false),
    },
    {
      id: "ALT-193",
      severity: "WARNING",
      state: "ACKNOWLEDGED",
      title: "Lifecycle projection lag above target",
      detail: "Lifecycle events remain below the hard stop threshold but exceed the preferred projection lag.",
      source: "Internal indexer",
      openedAt: "07:38:48 UTC",
      acknowledgedAt: "07:39:02 UTC",
      evidence: "RECORDED",
      freshness: fresh("47 s old", "60 s maximum", false),
    },
    {
      id: "ALT-188",
      severity: "NOTICE",
      state: "RESOLVED",
      title: "Keeper delay returned inside execution window",
      detail: "The delayed roll-preparation job received a lease before its committed checkpoint.",
      source: "Lifecycle keeper scheduler",
      openedAt: "07:27:06 UTC",
      resolvedAt: "07:32:41 UTC",
      evidence: "FIXTURE",
      freshness: fresh("8 m old", "15 m maximum"),
    },
  ],
  journal: [
    {
      id: "JRN-0831",
      at: "07:39:54 UTC",
      actor: "oracle-verifier",
      subject: "ALT-194",
      action: "Opened warning",
      detail: "Admission freshness threshold exceeded. Existing terminal resolution remains enabled.",
      evidence: "RECORDED",
    },
    {
      id: "JRN-0830",
      at: "07:39:43 UTC",
      actor: "keeper-scheduler",
      subject: "RCV-0042",
      action: "Queued resolution",
      detail: "Recovery action is bounded by the package residual and deadline.",
      evidence: "FIXTURE",
    },
    {
      id: "JRN-0829",
      at: "07:39:11 UTC",
      actor: "risk-policy",
      subject: "RCV-0042",
      action: "Stopped new risk",
      detail: "Admission is blocked for this recovery case without blocking objective completion.",
      evidence: "RECORDED",
    },
    {
      id: "JRN-0828",
      at: "07:39:02 UTC",
      actor: "operator-01",
      subject: "ALT-193",
      action: "Acknowledged alert",
      detail: "Lifecycle projection remains inside the operational maximum lag.",
      evidence: "RECORDED",
    },
  ],
};
