// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.37;

// Generated by scripts/generate-deploy-artifacts.mjs. Do not edit by hand.

/// @notice Standalone artifacts the deployment creates and the linked libraries they need, dependencies first.
library DeployArtifacts {
    struct LinkedLibrary {
        string artifact;
        string qualifiedName;
    }

    function linkedLibraries() internal pure returns (LinkedLibrary[] memory libraries) {
        libraries = new LinkedLibrary[](29);
        libraries[0] = LinkedLibrary(
            "AtomicClearingFundingLib.sol:AtomicClearingFundingLib",
            "src/execution/AtomicClearingFundingLib.sol:AtomicClearingFundingLib"
        );
        libraries[1] = LinkedLibrary(
            "AtomicClearingMatchLib.sol:AtomicClearingMatchLib",
            "src/execution/AtomicClearingMatchLib.sol:AtomicClearingMatchLib"
        );
        libraries[2] = LinkedLibrary(
            "AtomicClearingPackageLib.sol:AtomicClearingPackageLib",
            "src/execution/AtomicClearingPackageLib.sol:AtomicClearingPackageLib"
        );
        libraries[3] = LinkedLibrary(
            "AtomicClearingSeriesLib.sol:AtomicClearingSeriesLib",
            "src/execution/AtomicClearingSeriesLib.sol:AtomicClearingSeriesLib"
        );
        libraries[4] = LinkedLibrary(
            "CashSettlementContextLib.sol:CashSettlementContextLib",
            "src/settlement/CashSettlementContextLib.sol:CashSettlementContextLib"
        );
        libraries[5] = LinkedLibrary(
            "CashSettlementRecordLib.sol:CashSettlementRecordLib",
            "src/settlement/CashSettlementRecordLib.sol:CashSettlementRecordLib"
        );
        libraries[6] = LinkedLibrary(
            "CollateralReservationLib.sol:CollateralReservationLib",
            "src/collateral/CollateralReservationLib.sol:CollateralReservationLib"
        );
        libraries[7] = LinkedLibrary(
            "DefaultAuctionLib.sol:DefaultAuctionLib", "src/default/DefaultAuctionLib.sol:DefaultAuctionLib"
        );
        libraries[8] = LinkedLibrary(
            "DefaultOpeningLib.sol:DefaultOpeningLib", "src/default/DefaultOpeningLib.sol:DefaultOpeningLib"
        );
        libraries[9] = LinkedLibrary(
            "DefaultResolutionLib.sol:DefaultResolutionLib", "src/default/DefaultResolutionLib.sol:DefaultResolutionLib"
        );
        libraries[10] = LinkedLibrary(
            "OperationalExternalActionLib.sol:OperationalExternalActionLib",
            "src/adapters/operational/OperationalExternalActionLib.sol:OperationalExternalActionLib"
        );
        libraries[11] = LinkedLibrary(
            "PortfolioRiskAdmissionLib.sol:PortfolioRiskAdmissionLib",
            "src/risk/PortfolioRiskAdmissionLib.sol:PortfolioRiskAdmissionLib"
        );
        libraries[12] = LinkedLibrary(
            "PortfolioRiskExposureLib.sol:PortfolioRiskExposureLib",
            "src/risk/PortfolioRiskExposureLib.sol:PortfolioRiskExposureLib"
        );
        libraries[13] = LinkedLibrary(
            "PositionCreationLib.sol:PositionCreationLib", "src/position/PositionCreationLib.sol:PositionCreationLib"
        );
        libraries[14] = LinkedLibrary(
            "PositionTerminalLib.sol:PositionTerminalLib", "src/position/PositionTerminalLib.sol:PositionTerminalLib"
        );
        libraries[15] =
            LinkedLibrary("PositionViewLib.sol:PositionViewLib", "src/position/PositionViewLib.sol:PositionViewLib");
        libraries[16] = LinkedLibrary(
            "LifecycleBackingLib.sol:LifecycleBackingLib", "src/lifecycle/LifecycleBackingLib.sol:LifecycleBackingLib"
        );
        libraries[17] = LinkedLibrary(
            "LifecycleSuccessorLib.sol:LifecycleSuccessorLib",
            "src/lifecycle/LifecycleSuccessorLib.sol:LifecycleSuccessorLib"
        );
        libraries[18] = LinkedLibrary(
            "LifecycleActionLib.sol:LifecycleActionLib", "src/lifecycle/LifecycleActionLib.sol:LifecycleActionLib"
        );
        libraries[19] = LinkedLibrary(
            "PrivateRfqHandoffLib.sol:PrivateRfqHandoffLib", "src/rfq/PrivateRfqHandoffLib.sol:PrivateRfqHandoffLib"
        );
        libraries[20] = LinkedLibrary(
            "PrivateRfqLifecycleLib.sol:PrivateRfqLifecycleLib",
            "src/rfq/PrivateRfqLifecycleLib.sol:PrivateRfqLifecycleLib"
        );
        libraries[21] = LinkedLibrary(
            "PrivateRfqQuoteLib.sol:PrivateRfqQuoteLib", "src/rfq/PrivateRfqQuoteLib.sol:PrivateRfqQuoteLib"
        );
        libraries[22] = LinkedLibrary(
            "RouteSourceValidationLib.sol:RouteSourceValidationLib",
            "src/routing/RouteSourceValidationLib.sol:RouteSourceValidationLib"
        );
        libraries[23] = LinkedLibrary(
            "RouteSourceReservationLib.sol:RouteSourceReservationLib",
            "src/routing/RouteSourceReservationLib.sol:RouteSourceReservationLib"
        );
        libraries[24] = LinkedLibrary(
            "SealedAuctionBidLib.sol:SealedAuctionBidLib", "src/auction/SealedAuctionBidLib.sol:SealedAuctionBidLib"
        );
        libraries[25] = LinkedLibrary(
            "SealedAuctionClearingLib.sol:SealedAuctionClearingLib",
            "src/auction/SealedAuctionClearingLib.sol:SealedAuctionClearingLib"
        );
        libraries[26] = LinkedLibrary(
            "SealedAuctionSettlementLib.sol:SealedAuctionSettlementLib",
            "src/auction/SealedAuctionSettlementLib.sol:SealedAuctionSettlementLib"
        );
        libraries[27] = LinkedLibrary(
            "SeriesValidationLib.sol:SeriesValidationLib", "src/registry/SeriesValidationLib.sol:SeriesValidationLib"
        );
        libraries[28] = LinkedLibrary(
            "SeriesLifecycleLib.sol:SeriesLifecycleLib", "src/registry/SeriesLifecycleLib.sol:SeriesLifecycleLib"
        );
    }

    function artifactOf(string memory contractName) internal pure returns (string memory) {
        bytes32 key = keccak256(bytes(contractName));
        if (key == keccak256("AccountPolicyAuthority")) return "AccountPolicyAuthority.sol:AccountPolicyAuthority";
        if (key == keccak256("AdapterRegistry")) return "AdapterRegistry.sol:AdapterRegistry";
        if (key == keccak256("AssetRegistry")) return "AssetRegistry.sol:AssetRegistry";
        if (key == keccak256("AsyncReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:AsyncReceiptAuthority";
        if (key == keccak256("AtomicClearingEngine")) return "AtomicClearingEngine.sol:AtomicClearingEngine";
        if (key == keccak256("AuctionReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:AuctionReceiptAuthority";
        }
        if (key == keccak256("AuctionValidationGate")) return "AuctionValidationGate.sol:AuctionValidationGate";
        if (key == keccak256("BasisSpreadPayoffModule")) return "ProductionPayoffModules.sol:BasisSpreadPayoffModule";
        if (key == keccak256("BatchClearingEngine")) return "BatchClearingEngine.sol:BatchClearingEngine";
        if (key == keccak256("BenchmarkRegistry")) return "BenchmarkRegistry.sol:BenchmarkRegistry";
        if (key == keccak256("BookOrderReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:BookOrderReceiptAuthority";
        }
        if (key == keccak256("CalendarRegistry")) return "CalendarRegistry.sol:CalendarRegistry";
        if (key == keccak256("CalendarSpreadPayoffModule")) {
            return "ProductionPayoffModules.sol:CalendarSpreadPayoffModule";
        }
        if (key == keccak256("CanonicalStrategyCompiler")) {
            return "CanonicalStrategyCompiler.sol:CanonicalStrategyCompiler";
        }
        if (key == keccak256("CapacityReservationRegistry")) {
            return "CapacityReservationRegistry.sol:CapacityReservationRegistry";
        }
        if (key == keccak256("CappedForwardPayoffModule")) {
            return "ProductionPayoffModules.sol:CappedForwardPayoffModule";
        }
        if (key == keccak256("CashSettlementCoordinator")) {
            return "CashSettlementCoordinator.sol:CashSettlementCoordinator";
        }
        if (key == keccak256("ClearingAdmissionGate")) return "ClearingAdmissionGate.sol:ClearingAdmissionGate";
        if (key == keccak256("CollarPayoffModule")) return "ProductionPayoffModules.sol:CollarPayoffModule";
        if (key == keccak256("CollateralAwareRouteEngine")) {
            return "CollateralAwareRouteEngine.sol:CollateralAwareRouteEngine";
        }
        if (key == keccak256("CollateralVault")) return "CollateralVault.sol:CollateralVault";
        if (key == keccak256("CompressionCoordinator")) return "CompressionCoordinator.sol:CompressionCoordinator";
        if (key == keccak256("CorrelationDispersionScalarPayoffModule")) {
            return "ProductionPayoffModules.sol:CorrelationDispersionScalarPayoffModule";
        }
        if (key == keccak256("DefaultBidderGate")) return "DefaultBidderGate.sol:DefaultBidderGate";
        if (key == keccak256("DefaultProcessEngine")) return "DefaultProcessEngine.sol:DefaultProcessEngine";
        if (key == keccak256("DefaultReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:DefaultReceiptAuthority";
        }
        if (key == keccak256("DevnetSequencerUptimeFeed")) {
            return "DevnetSequencerUptimeFeed.sol:DevnetSequencerUptimeFeed";
        }
        if (key == keccak256("EuropeanCallPayoffModule")) {
            return "ProductionPayoffModules.sol:EuropeanCallPayoffModule";
        }
        if (key == keccak256("EuropeanPutPayoffModule")) return "ProductionPayoffModules.sol:EuropeanPutPayoffModule";
        if (key == keccak256("ExecutionPolicyRegistry")) return "ExecutionPolicyRegistry.sol:ExecutionPolicyRegistry";
        if (key == keccak256("FeeReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:FeeReceiptAuthority";
        if (key == keccak256("FeeScheduleRegistry")) return "FeeScheduleRegistry.sol:FeeScheduleRegistry";
        if (key == keccak256("FillReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:FillReceiptAuthority";
        if (key == keccak256("FixingEngine")) return "FixingEngine.sol:FixingEngine";
        if (key == keccak256("FixingReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:FixingReceiptAuthority";
        if (key == keccak256("FundedFeeEngine")) return "FundedFeeEngine.sol:FundedFeeEngine";
        if (key == keccak256("InstrumentRegistry")) return "InstrumentRegistry.sol:InstrumentRegistry";
        if (key == keccak256("LifecyclePolicyValidator")) {
            return "LifecyclePolicyValidator.sol:LifecyclePolicyValidator";
        }
        if (key == keccak256("LifecycleReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:LifecycleReceiptAuthority";
        }
        if (key == keccak256("MarketRegistry")) return "MarketRegistry.sol:MarketRegistry";
        if (key == keccak256("NdfPayoffModule")) return "ProductionPayoffModules.sol:NdfPayoffModule";
        if (key == keccak256("OperationalAdapterExecutor")) {
            return "OperationalAdapterExecutor.sol:OperationalAdapterExecutor";
        }
        if (key == keccak256("OrderReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:OrderReceiptAuthority";
        if (key == keccak256("OrderState")) return "OrderState.sol:OrderState";
        if (key == keccak256("OrderValidationGate")) return "OrderValidationGate.sol:OrderValidationGate";
        if (key == keccak256("PackageRegistry")) return "PackageRegistry.sol:PackageRegistry";
        if (key == keccak256("PackageWitnessRegistry")) return "PackageWitnessRegistry.sol:PackageWitnessRegistry";
        if (key == keccak256("PortfolioRiskEngine")) return "PortfolioRiskEngine.sol:PortfolioRiskEngine";
        if (key == keccak256("PositionEngine")) return "PositionEngine.sol:PositionEngine";
        if (key == keccak256("PositionLifecycleExecutor")) {
            return "PositionLifecycleExecutor.sol:PositionLifecycleExecutor";
        }
        if (key == keccak256("PositionReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:PositionReceiptAuthority";
        }
        if (key == keccak256("PrivacyCommitmentRegistry")) {
            return "PrivacyCommitmentRegistry.sol:PrivacyCommitmentRegistry";
        }
        if (key == keccak256("PrivacyReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:PrivacyReceiptAuthority";
        }
        if (key == keccak256("PrivateRfqBook")) return "PrivateRfqBook.sol:PrivateRfqBook";
        if (key == keccak256("PrivateRfqValidationGate")) {
            return "PrivateRfqValidationGate.sol:PrivateRfqValidationGate";
        }
        if (key == keccak256("ProtocolRouteLiquiditySource")) {
            return "ProtocolRouteLiquiditySource.sol:ProtocolRouteLiquiditySource";
        }
        if (key == keccak256("PublicBookEligibilityGate")) {
            return "PublicBookEligibilityGate.sol:PublicBookEligibilityGate";
        }
        if (key == keccak256("PublicOrderBook")) return "PublicOrderBook.sol:PublicOrderBook";
        if (key == keccak256("QuoteSettlementRouter")) return "QuoteSettlementRouter.sol:QuoteSettlementRouter";
        if (key == keccak256("RateCapPayoffModule")) return "ProductionPayoffModules.sol:RateCapPayoffModule";
        if (key == keccak256("RateCollarPayoffModule")) return "ProductionPayoffModules.sol:RateCollarPayoffModule";
        if (key == keccak256("RateFloorPayoffModule")) return "ProductionPayoffModules.sol:RateFloorPayoffModule";
        if (key == keccak256("RateForwardPayoffModule")) return "ProductionPayoffModules.sol:RateForwardPayoffModule";
        if (key == keccak256("RecoveryReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:RecoveryReceiptAuthority";
        }
        if (key == keccak256("RegistryStatusController")) {
            return "RegistryStatusController.sol:RegistryStatusController";
        }
        if (key == keccak256("RfqReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:RfqReceiptAuthority";
        if (key == keccak256("RiskAdmissionBindingRegistry")) {
            return "RiskAdmissionBindingRegistry.sol:RiskAdmissionBindingRegistry";
        }
        if (key == keccak256("RiskDomainRegistry")) return "RiskDomainRegistry.sol:RiskDomainRegistry";
        if (key == keccak256("RiskReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:RiskReceiptAuthority";
        if (key == keccak256("RouteReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:RouteReceiptAuthority";
        if (key == keccak256("SealedAuctionHouse")) return "SealedAuctionHouse.sol:SealedAuctionHouse";
        if (key == keccak256("SeriesRegistry")) return "SeriesRegistry.sol:SeriesRegistry";
        if (key == keccak256("SessionRegistry")) return "SessionRegistry.sol:SessionRegistry";
        if (key == keccak256("SettlementAssetRegistry")) return "SettlementAssetRegistry.sol:SettlementAssetRegistry";
        if (key == keccak256("SettlementReceiptAuthority")) {
            return "ProtocolReceiptAuthorities.sol:SettlementReceiptAuthority";
        }
        if (key == keccak256("SignedLifecycleEngine")) return "SignedLifecycleEngine.sol:SignedLifecycleEngine";
        if (key == keccak256("SolverReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:SolverReceiptAuthority";
        if (key == keccak256("StreamReceiptAuthority")) return "ProtocolReceiptAuthorities.sol:StreamReceiptAuthority";
        if (key == keccak256("StreamingQuoteEngine")) return "StreamingQuoteEngine.sol:StreamingQuoteEngine";
        if (key == keccak256("TradingSessionPolicy")) return "TradingSessionPolicy.sol:TradingSessionPolicy";
        if (key == keccak256("VaultBackedBatchCapacityManager")) {
            return "VaultBackedBatchCapacityManager.sol:VaultBackedBatchCapacityManager";
        }
        if (key == keccak256("VaultBackedStreamCapacityManager")) {
            return "VaultBackedStreamCapacityManager.sol:VaultBackedStreamCapacityManager";
        }
        if (key == keccak256("VerifiableReceiptLedger")) return "VerifiableReceiptLedger.sol:VerifiableReceiptLedger";
        if (key == keccak256("WindowAverageScalarPayoffModule")) {
            return "ProductionPayoffModules.sol:WindowAverageScalarPayoffModule";
        }
        revert("DeployArtifacts: unknown contract");
    }
}
