import { DEFAULT_RATE_LIMIT } from "./keys";
import { SIGNATURE_VERSION, TIMESTAMP_WINDOW_SECONDS } from "./replay";

/** OpenAPI 3.1 description of the v1 public API. Served at /api/v1/openapi.json. */

type Schema = Record<string, unknown>;

const ref = (name: string): Schema => ({ $ref: `#/components/schemas/${name}` });
const hex = (length?: number): Schema => ({ type: "string", pattern: length ? `^0x[0-9a-fA-F]{${length}}$` : "^0x[0-9a-fA-F]*$" });
const integerString: Schema = { type: "string", pattern: "^-?\\d+$" };
const dateTime: Schema = { type: "string", format: "date-time" };
const object = (properties: Record<string, Schema>, required = Object.keys(properties)): Schema => ({
  type: "object",
  properties,
  required,
});
const nullable = (schema: Schema): Schema => ({ oneOf: [schema, { type: "null" }] });
const dataOf = (schema: Schema): Schema => object({ data: schema });
const pageOf = (item: Schema): Schema =>
  object({
    data: { type: "array", items: item },
    page: object({ limit: { type: "integer" }, nextCursor: nullable({ type: "string" }), total: { type: "integer" } }),
  });

const errorResponses = (...codes: number[]) =>
  Object.fromEntries(
    codes.map((code) => [
      String(code),
      {
        description: {
          400: "Invalid request",
          401: "Missing, invalid or revoked API key, bad signature, or stale timestamp",
          403: "Insufficient scope, signer not allowed, or console not local",
          404: "Not found",
          409: "Rejected by market, book, position or replay state",
          422: "Risk admission refused the order",
          429: "Rate limited. See Retry-After and RateLimit-* headers",
          503: "Deployment or chain RPC unavailable",
        }[code],
        content: { "application/json": { schema: ref("Error") } },
      },
    ]),
  );

const pagingParameters = [
  { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 200, default: 50 } },
  { name: "cursor", in: "query", schema: { type: "string" }, description: "Opaque cursor from page.nextCursor." },
];
const accountFilter = [
  { name: "accountId", in: "query", schema: hex(64), description: "Collateral account id. Either accountId or signer is required." },
  { name: "signer", in: "query", schema: hex(40), description: "Order signer; resolves to the signer's primary account." },
];
const marketIdParameter = { name: "marketId", in: "path", required: true, schema: { type: "string" }, example: "BTC-YC-24DEC26" };
const readSecurity = [{ bearer: [] }];
const writeSecurity = [{ bearer: [], timestamp: [], nonce: [], signature: [] }];

const get = (summary: string, schema: Schema, extra: Schema = {}) => ({
  get: {
    summary,
    security: readSecurity,
    "x-setryn-scope": "read",
    responses: { 200: { description: "OK", content: { "application/json": { schema } } }, ...errorResponses(400, 401, 403, 404, 429, 503) },
    ...extra,
  },
});

const rfqIdParameter = { name: "rfqId", in: "path", required: true, schema: hex(64) };
const write = (summary: string, description: string, request: Schema | null, status: number, response: Schema, codes: number[], extra: Schema = {}) => ({
  post: {
    summary,
    description,
    tags: ["RFQ"],
    security: writeSecurity,
    "x-setryn-scope": "trade",
    ...(request ? { requestBody: { required: true, content: { "application/json": { schema: request } } } } : {}),
    responses: { [status]: { description: "OK", content: { "application/json": { schema: response } } }, ...errorResponses(...codes) },
    ...extra,
  },
});

const OPERATION_IDS: Record<string, string> = {
  "get /status": "getStatus",
  "get /markets": "listMarkets",
  "get /markets/{marketId}": "getMarket",
  "get /markets/{marketId}/book": "getBook",
  "get /markets/{marketId}/trades": "listTrades",
  "get /accounts/{accountId}": "getAccount",
  "get /accounts/{accountId}/positions": "listPositions",
  "get /fills": "listFills",
  "get /receipts": "listReceipts",
  "get /orders": "listOrders",
  "post /orders": "submitOrder",
  "post /orders/prepare": "prepareOrder",
  "get /orders/{orderHash}": "getOrder",
  "post /positions/exit/prepare": "prepareExit",
  "post /positions/exit": "submitExit",
  "get /rfqs": "listRfqs",
  "post /rfqs": "submitRfq",
  "post /rfqs/prepare": "prepareRfq",
  "get /rfqs/{rfqId}": "getRfq",
  "get /rfqs/{rfqId}/quotes": "listRfqQuotes",
  "post /rfqs/{rfqId}/quotes": "solicitRfqQuotes",
  "post /rfqs/{rfqId}/accept/prepare": "prepareRfqAcceptance",
  "post /rfqs/{rfqId}/accept": "acceptRfqQuote",
  "post /rfqs/{rfqId}/settle": "settleRfq",
  "post /rfqs/{rfqId}/cancel": "prepareRfqCancel",
  "get /keys": "listKeys",
  "post /keys": "issueKey",
  "delete /keys/{keyId}": "revokeKey",
  "get /openapi.json": "getOpenApi",
};

/** Operation ids match the @setryn/sdk method names. */
function withOperationIds<T extends { paths: Record<string, Record<string, Record<string, unknown>>> }>(document: T): T {
  for (const [path, operations] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(operations)) {
      const id = OPERATION_IDS[`${method} ${path}`];
      if (id) operation.operationId = id;
    }
  }
  return document;
}

export function openApiDocument(serverUrl: string) {
  return withOperationIds({
    openapi: "3.1.0",
    info: {
      title: "Setryn Public API",
      version: "1.0.0",
      summary: "Versioned read and order-relay API over the Setryn contracts.",
      description: [
        "Every response is derived from the same contract state and events as the Setryn platform. The API never holds user keys and never sends transactions for a user: orders and private RFQs are prepared as EIP-712 typed data, signed locally, and relayed through the platform's risk admission path, which returns the exact transactions the signer sends.",
        "",
        "**Markets.** Every catalog market listed in the deployment runtime executes onchain (`execution: ONCHAIN`) on its own series, public book, price grid (`onchain.priceScale` and `onchain.priceOffset`: priceTicks = (price - priceOffset) x priceScale), tick size, lot cap and collateral per lot. Each market is a cash-settled dated range forward: the long receives lotSize x clamp(fixing - floor, 0, cap - floor) at expiry, and the quoted price is the forward level.",
        "",
        "**Versioning.** The major version is in the path (`/api/v1`). Additive changes (new fields, endpoints, enum members announced in advance) ship within v1. Breaking changes ship as `/api/v2`, and v1 keeps serving for at least 90 days after v2 is announced, with a `Deprecation` and `Sunset` header during that window. Every response carries `Setryn-Api-Version` and `Setryn-Request-Id`.",
        "",
        "**Authentication.** `Authorization: Bearer stk_...`. Keys carry scopes `read` and `trade` and may be restricted to specific signer addresses.",
        "",
        `**Rate limits.** Per-key token bucket, default capacity ${DEFAULT_RATE_LIMIT.capacity} with ${DEFAULT_RATE_LIMIT.refillPerSecond} tokens/s refill. Every response carries RateLimit-Limit, RateLimit-Remaining, RateLimit-Reset and RateLimit-Policy; a refused request gets 429 with Retry-After. Keys issued under a partner deployment also share that partner's apiRequestsPerMinute quota (Setryn-Partner-Quota-Limit and Setryn-Partner-Quota-Remaining headers); a paused partner's keys get 403 PARTNER_INACTIVE.`,
        "",
        `**Replay protection.** Every write (POST/DELETE) needs Setryn-Timestamp (unix seconds within ±${TIMESTAMP_WINDOW_SECONDS}s), a fresh Setryn-Nonce (16-128 chars of [A-Za-z0-9_-], single use per key) and Setryn-Signature: hex HMAC-SHA256 keyed with SHA-256(apiKey) (32 raw bytes) over \`${SIGNATURE_VERSION}\\nMETHOD\\npath?query\\ntimestamp\\nnonce\\nhex(SHA-256(body))\`.`,
        "",
        "**Errors.** Always `{ \"error\": { \"code\", \"message\" } }` with a stable code.",
        "",
        "**Service objectives.** Reads answer from chain state at the current head block and are memoized per block. There is no availability commitment yet for any deployment.",
      ].join("\n"),
    },
    servers: [{ url: `${serverUrl}/api/v1` }],
    tags: [{ name: "Markets" }, { name: "Accounts" }, { name: "Orders" }, { name: "RFQ" }, { name: "Positions" }, { name: "System" }, { name: "Keys" }],
    paths: {
      "/status": get("Chain, head block and deployment evidence summary", dataOf(ref("Status")), { tags: ["System"] }),
      "/markets": get("List markets", pageOf(ref("Market")), { tags: ["Markets"], parameters: pagingParameters }),
      "/markets/{marketId}": get("Get one market", dataOf(ref("Market")), { tags: ["Markets"], parameters: [marketIdParameter] }),
      "/markets/{marketId}/book": get(
        "Order book: the live direct book of the market's active series. A market the deployment does not list onchain answers 409 MARKET_NOT_ONCHAIN.",
        dataOf(ref("Book")),
        { tags: ["Markets"], parameters: [marketIdParameter] },
      ),
      "/markets/{marketId}/trades": get(
        "Trade tape, newest first: onchain direct-book fills of the market's series (private RFQ fills stay off the public tape). A market the deployment does not list onchain answers 409 MARKET_NOT_ONCHAIN.",
        pageOf(ref("Trade")),
        { tags: ["Markets"], parameters: [marketIdParameter, ...pagingParameters] },
      ),
      "/accounts/{accountId}": get("Collateral balance of an account", dataOf(ref("Account")), {
        tags: ["Accounts"],
        parameters: [{ name: "accountId", in: "path", required: true, schema: hex(64) }],
      }),
      "/accounts/{accountId}/positions": get("Live positions of an account", pageOf(ref("Position")), {
        tags: ["Accounts"],
        parameters: [{ name: "accountId", in: "path", required: true, schema: hex(64) }, ...pagingParameters],
      }),
      "/fills": get("Fills of an account, newest first", pageOf(ref("Fill")), { tags: ["Accounts"], parameters: [...accountFilter, ...pagingParameters] }),
      "/receipts": get("Execution receipts of an account, newest first", pageOf(ref("Receipt")), {
        tags: ["Accounts"],
        parameters: [...accountFilter, ...pagingParameters],
      }),
      "/orders": {
        ...get("Registered orders of an account or signer, newest first", pageOf(ref("Order")), {
          tags: ["Orders"],
          parameters: [
            ...accountFilter,
            { name: "state", in: "query", schema: { type: "string", enum: ["WORKING", "PARTIALLY_FILLED", "FILLED", "CANCELLED", "EXPIRED"] } },
            ...pagingParameters,
          ],
        }),
        post: {
          summary: "Relay a signed order to risk admission and get the transactions to send",
          description:
            "Verifies the EIP-712 signature, checks marketability, and runs the platform's risk admission for the order. Returns the transactions the signer must send in order. Requires scope `trade` and replay protection headers.",
          tags: ["Orders"],
          security: writeSecurity,
          "x-setryn-scope": "trade",
          requestBody: { required: true, content: { "application/json": { schema: ref("SubmitOrderRequest") } } },
          responses: {
            202: { description: "Risk reserved; send the returned transactions", content: { "application/json": { schema: dataOf(ref("SubmitOrderResult")) } } },
            ...errorResponses(400, 401, 403, 409, 422, 429, 503),
          },
        },
      },
      "/orders/prepare": {
        post: {
          summary: "Build an unsigned public order and its EIP-712 typed data",
          tags: ["Orders"],
          security: writeSecurity,
          "x-setryn-scope": "trade",
          requestBody: { required: true, content: { "application/json": { schema: ref("PrepareOrderRequest") } } },
          responses: {
            200: { description: "Unsigned order", content: { "application/json": { schema: dataOf(ref("PreparedOrder")) } } },
            ...errorResponses(400, 401, 403, 404, 409, 429, 503),
          },
        },
      },
      "/orders/{orderHash}": get("One registered order", dataOf(ref("Order")), {
        tags: ["Orders"],
        parameters: [{ name: "orderHash", in: "path", required: true, schema: hex(64) }],
      }),
      "/orders/{orderHash}/cancel": {
        post: {
          summary: "Prepare the cancellation of a working order: transactions to send and the risk-release message to sign",
          tags: ["Orders"],
          security: writeSecurity,
          "x-setryn-scope": "trade",
          parameters: [{ name: "orderHash", in: "path", required: true, schema: hex(64) }],
          responses: {
            200: {
              description: "Cancellation to execute from the order's signer",
              content: { "application/json": { schema: { type: "object", properties: { data: { type: "object" } } } } },
            },
            ...errorResponses(400, 401, 403, 404, 409, 429, 503),
          },
        },
      },
      "/positions/exit/prepare": {
        post: {
          summary: "Build the full lifecycle exit of a position and its opposite closing position",
          description:
            "Pairs an open position with the opposite position that closes it (opened by an opposite-side order through /orders). Both must be between the signer's account and the same counterparty, with equal lots and no package provenance. Returns the kind-4 LifecycleAction, its inputs and collateral replacements, the counterparty's consent and consent signature, and the SetrynLifecycleActionV1 typed data for the signer to sign. The counterparty consent comes from the platform's designated maker, which consents only for positions it is the counterparty of. Nothing is sent onchain. Refusals use code EXIT_NOT_ELIGIBLE.",
          tags: ["Positions"],
          security: writeSecurity,
          "x-setryn-scope": "trade",
          requestBody: { required: true, content: { "application/json": { schema: ref("PrepareExitRequest") } } },
          responses: {
            200: { description: "Unsigned exit with counterparty consent", content: { "application/json": { schema: dataOf(ref("PreparedExit")) } } },
            ...errorResponses(400, 401, 403, 404, 409, 429, 503),
          },
        },
      },
      "/positions/exit": {
        post: {
          summary: "Verify a signed lifecycle exit and get the authorize and execute transactions to send",
          description:
            "Re-derives the action id from the submitted action and checks it against the consent, checks the committed input and replacement hashes, verifies the consent and actor signatures, and simulates authorizeAction from the signer. Returns AUTHORIZE_LIFECYCLE and EXECUTE_LIFECYCLE for the signer to send in order. Requires scope `trade` and replay protection headers.",
          tags: ["Positions"],
          security: writeSecurity,
          "x-setryn-scope": "trade",
          requestBody: { required: true, content: { "application/json": { schema: ref("SubmitExitRequest") } } },
          responses: {
            200: { description: "Send the returned transactions", content: { "application/json": { schema: dataOf(ref("SubmitExitResult")) } } },
            ...errorResponses(400, 401, 403, 409, 429, 503),
          },
        },
      },
      "/rfqs": {
        ...get("Private RFQs requested by an account or signer, newest first", pageOf(ref("Rfq")), {
          tags: ["RFQ"],
          parameters: [
            ...accountFilter,
            { name: "state", in: "query", schema: { type: "string", enum: RFQ_STATES } },
            ...pagingParameters,
          ],
        }),
        ...write(
          "Relay a signed private RFQ order and request to risk admission and get the transactions to send",
          "Verifies the PublicOrder and PrivateRfqRequest signatures, checks that the request is exactly the one derived from the order (taker, series, side, size, fee cap, deadline and the deployment's private RFQ privacy, execution and disclosure terms), and runs the platform's risk admission for the taker order. Returns APPROVE_LOCK_OPERATOR when missing, BIND_RISK, REGISTER_ORDER, REGISTER_RFQ and OPEN_RFQ for the requester to send in order. A key restricted to signers can only submit for those signers.",
          ref("SubmitRfqRequest"),
          202,
          dataOf(ref("SubmitRfqResult")),
          [400, 401, 403, 409, 422, 429, 503],
        ),
      },
      "/rfqs/prepare": write(
        "Build an unsigned private RFQ: the taker order and the request bound to it",
        "Builds the taker's PublicOrder on the market's series with the private RFQ execution mode, its price grid, lot cap and collateral per lot, and the PrivateRfqRequest committing to it. Returns both EIP-712 typed data (PublicOrder on OrderState, PrivateRfqRequest on the PrivateRfqBook). timeInForce defaults to IOC; FOK is refused because the RFQ book requires a no-partial-fill request to keep its remainder open. limitPrice is the worst price the requester accepts. Nothing is sent onchain.",
        ref("PrepareRfqRequest"),
        200,
        dataOf(ref("PreparedRfq")),
        [400, 401, 403, 404, 409, 429, 503],
      ),
      "/rfqs/{rfqId}": get("One private RFQ with its quotes", dataOf(ref("Rfq")), { tags: ["RFQ"], parameters: [rfqIdParameter] }),
      "/rfqs/{rfqId}/quotes": {
        ...get("Quotes on an RFQ, best price for the requester first", pageOf(ref("RfqQuote")), {
          tags: ["RFQ"],
          parameters: [rfqIdParameter, ...pagingParameters],
        }),
        ...write(
          "Invite the eligible solvers to quote an RFQ that is collecting",
          "The RFQ must be COLLECTING (OPEN_RFQ sent). Where the deployment runs a designated maker, it quotes from the live reference price the same way the terminal triggers it: it registers a risk-bound backing order, submits a signed firm quote and reserves its capacity. Returns the RFQ's quotes.",
          null,
          200,
          dataOf(ref("SolicitQuotesResult")),
          [400, 401, 403, 404, 409, 429, 503],
          { parameters: [rfqIdParameter] },
        ),
      },
      "/rfqs/{rfqId}/accept/prepare": write(
        "Build the unsigned selection of one quote",
        "The quote must be RESERVED (firm capacity locked) and at or inside the requester's signed limit (withinLimit). Returns the RfqSelectionAuthorization typed data on the PrivateRfqBook, with a deadline no later than the RFQ's and the quote's.",
        object({ quoteId: hex(64) }),
        200,
        dataOf(ref("PreparedRfqAcceptance")),
        [400, 401, 403, 404, 409, 429, 503],
        { parameters: [rfqIdParameter] },
      ),
      "/rfqs/{rfqId}/accept": write(
        "Verify a signed quote selection and get the transactions to send",
        "Verifies the selection signature and terms, simulates lockSelection from the requester, and returns LOCK_SELECTION, CONFIRM_CAPACITY, AUTHORIZE_SUBMISSION and SUBMIT_RFQ for the requester to send in order.",
        object({ selection: ref("SerializedRfqSelection"), signature: hex() }),
        200,
        dataOf(ref("AcceptRfqResult")),
        [400, 401, 403, 404, 409, 429, 503],
        { parameters: [rfqIdParameter] },
      ),
      "/rfqs/{rfqId}/settle": write(
        "Hand a submitted RFQ to its permitted executor for atomic clearing",
        "The RFQ must be SUBMITTED. The executor clears the selected quote through AtomicClearingEngine.clearSeriesWithHandoff; the executor is the platform operator. Returns the fill, position and fees. Settling a SETTLED RFQ returns its settlement again.",
        null,
        200,
        dataOf(ref("RfqSettlement")),
        [400, 401, 403, 404, 409, 429, 503],
        { parameters: [rfqIdParameter] },
      ),
      "/rfqs/{rfqId}/cancel": write(
        "Prepare the cancellation of an unselected or expired RFQ",
        "Returns CANCEL_RFQ (cancelRfq while INVITING or COLLECTING, expireRfq past the deadline) and the risk-release message whose signature frees the collateral reserved for the taker order.",
        null,
        200,
        { type: "object", properties: { data: { type: "object" } } },
        [400, 401, 403, 404, 409, 429, 503],
        { parameters: [rfqIdParameter] },
      ),
      "/keys": {
        get: {
          summary: "List API keys with usage, rate-limit state and recent requests (local console only)",
          tags: ["Keys"],
          security: [],
          responses: { 200: { description: "OK", content: { "application/json": { schema: dataOf({ type: "array", items: ref("ApiKey") }) } } }, ...errorResponses(403) },
        },
        post: {
          summary: "Issue an API key (local console only). The key is returned once.",
          tags: ["Keys"],
          security: [],
          requestBody: { required: true, content: { "application/json": { schema: ref("IssueKeyRequest") } } },
          responses: {
            201: { description: "Issued", content: { "application/json": { schema: dataOf(object({ key: { type: "string" }, record: ref("ApiKey") })) } } },
            ...errorResponses(400, 403, 409),
          },
        },
      },
      "/keys/{keyId}": {
        delete: {
          summary: "Revoke an API key (local console only)",
          tags: ["Keys"],
          security: [],
          parameters: [{ name: "keyId", in: "path", required: true, schema: { type: "string", pattern: "^[0-9a-f]{12}$" } }],
          responses: { 200: { description: "Revoked", content: { "application/json": { schema: dataOf(ref("ApiKey")) } } }, ...errorResponses(403, 404) },
        },
      },
      "/openapi.json": { get: { summary: "This document", tags: ["System"], security: [], responses: { 200: { description: "OpenAPI 3.1 document" } } } },
    },
    components: {
      securitySchemes: {
        bearer: { type: "http", scheme: "bearer", bearerFormat: "stk_test_<id>_<secret>" },
        timestamp: { type: "apiKey", in: "header", name: "Setryn-Timestamp" },
        nonce: { type: "apiKey", in: "header", name: "Setryn-Nonce" },
        signature: { type: "apiKey", in: "header", name: "Setryn-Signature" },
      },
      schemas: {
        Error: object({ error: object({ code: { type: "string" }, message: { type: "string" } }) }),
        Status: object({
          environment: { type: "string" },
          chainId: { type: "integer" },
          headBlock: integerString,
          headTime: dateTime,
          chainTime: dateTime,
          deployment: object({
            status: { type: "string" },
            sourceCommit: nullable({ type: "string" }),
            contracts: { type: "integer" },
            matching: { type: "integer" },
            state: { type: "string", enum: ["VERIFIED", "DEGRADED"] },
          }),
          onchainMarkets: { type: "array", items: { type: "string" }, description: "Catalog ids of the markets that execute onchain." },
          settlement: object({ token: hex(40), assetId: hex(64), collateralSymbol: { type: "string" }, decimals: { type: "integer" } }),
          contracts: { type: "object", additionalProperties: hex(40) },
        }),
        Market: object({
          id: { type: "string" },
          name: { type: "string" },
          code: { type: "string" },
          underlying: { type: "string" },
          strategyKind: { type: "string" },
          strategyLabel: { type: "string" },
          priceUnit: { type: "string" },
          priceDecimals: { type: "integer" },
          tickSize: { type: "number" },
          tenorLabel: { type: "string" },
          expiry: { type: "string" },
          settlementClass: { type: "string" },
          settlementAsset: { type: "string" },
          fixingSource: { type: "string" },
          qualification: { type: "string", enum: ["QUALIFIED", "CONDITIONAL", "SUSPENDED"] },
          qualificationNote: { type: "string" },
          contractMultiplier: { type: "number" },
          collateralPerLot: { type: "number" },
          maxOrderLots: nullable({ type: "integer" }),
          execution: { type: "string", enum: ["ONCHAIN"] },
          onchain: nullable(
            object({
              chainId: { type: "integer" },
              seriesId: hex(64),
              marketId: hex(64),
              bookId: hex(64),
              orderState: hex(40),
              publicOrderBook: hex(40),
              privateRfqBook: hex(40),
              tickSizeMinor: { type: "integer", description: "Settlement minor units per price tick per lot." },
              priceScale: { type: "integer", description: "Price ticks per unit of package price: priceTicks = (price - priceOffset) x priceScale. Prices must sit on this grid." },
              priceOffset: { type: "number", description: "Price at zero ticks (the range forward's floor)." },
              maxOrderLots: { type: "integer" },
              maxLongDebitMinorPerLot: { type: "integer" },
              maxShortDebitMinorPerLot: { type: "integer" },
              seriesVersion: { type: "integer", description: "The series' active version: the targetVersion orders sign. A fee change re-versions every series." },
              feeScheduleId: hex(64),
              feeScheduleVersion: { type: "integer", description: "The fee schedule version the registry has active. Orders must sign this version; the book is keyed by it." },
              makerFeeRatePpm: { type: "integer", description: "Active maker charge rate against 1,000,000 (100 = 1 bp), read from chain." },
              takerFeeRatePpm: { type: "integer", description: "Active taker charge rate against 1,000,000 (100 = 1 bp), read from chain." },
              makerFlatFeeMinor: { type: "integer", description: "Flat maker charge per fill in settlement minor units." },
              takerFlatFeeMinor: { type: "integer", description: "Flat taker charge per fill in settlement minor units." },
              feeSource: { type: "string", enum: ["CHAIN", "RUNTIME"], description: "RUNTIME when the chain was unreachable and the deployment's recorded rates were used." },
            }),
          ),
          quote: object({
            source: { type: "string", enum: ["MARKET_DATA", "LISTING_REFERENCE"], description: "MARKET_DATA once the live feed was read; LISTING_REFERENCE when only the listing is available." },
            netPrice: nullable({ type: "number", description: "The mark: book mid, else the last fill, else the Chainlink reference (see markSource)." }),
            markSource: { type: "string", enum: ["MID", "LAST", "REFERENCE", "NONE"] },
            priorNetPrice: nullable({ type: "number", description: "First fill price in the last 24 hours." }),
            bestBid: nullable({ type: "number" }),
            bestAsk: nullable({ type: "number" }),
            referencePrice: nullable({ type: "number", description: "Chainlink reference of the underlying on Arbitrum." }),
          }),
          terms: object({
            floor: { type: "number" },
            cap: { type: "number" },
            lotSize: { type: "number", description: "Units of the underlying per lot." },
            expiryAt: dateTime,
            lastTradingAt: dateTime,
          }),
          legs: { type: "array", items: object({ id: { type: "string" }, side: { type: "string", enum: ["BUY", "SELL"] }, ratio: { type: "number" } }) },
        }),
        BookLevel: object({ price: { type: "number" }, lots: { type: "integer" }, priceTicks: integerString, orders: { type: "integer" } }, ["price", "lots"]),
        Book: object(
          {
            marketId: { type: "string" },
            source: { type: "string", enum: ["ONCHAIN_PUBLIC_BOOK"] },
            executable: { type: "boolean" },
            seriesId: hex(64),
            bookId: hex(64),
            priceScale: { type: "integer" },
            priceOffset: { type: "number", description: "Price at zero ticks (the range forward's floor): price = priceOffset + priceTicks / priceScale." },
            headBlock: integerString,
            chainTime: dateTime,
            bids: { type: "array", items: ref("BookLevel") },
            asks: { type: "array", items: ref("BookLevel") },
            note: { type: "string" },
          },
          ["marketId", "source", "executable", "bids", "asks"],
        ),
        Trade: object(
          {
            tradeId: { type: "string" },
            marketId: { type: "string" },
            price: { type: "number" },
            priceTicks: integerString,
            lots: { type: "integer" },
            aggressorSide: { type: "string", enum: ["BUY", "SELL"] },
            route: { type: "string", enum: ["DIRECT_BOOK"] },
            transactionHash: hex(64),
            time: dateTime,
            source: { type: "string", enum: ["ONCHAIN_FILL"] },
          },
          ["tradeId", "marketId", "price", "lots", "aggressorSide", "time", "source"],
        ),
        Account: object({
          accountId: hex(64),
          exists: { type: "boolean" },
          collateralAsset: { type: "string" },
          collateralId: hex(64),
          postedUsd: { type: "number" },
          reservedUsd: { type: "number" },
          availableUsd: { type: "number" },
          postedMinor: integerString,
          reservedMinor: integerString,
          availableMinor: integerString,
        }),
        Position: object({
          positionId: hex(64),
          marketId: { type: "string" },
          side: { type: "string", enum: ["LONG", "SHORT"] },
          lots: { type: "integer" },
          entryPrice: { type: "number" },
          entryPriceTicks: integerString,
          collateralUsd: { type: "number" },
          state: { const: "ACTIVE" },
          openedByFillId: hex(64),
          transactionHash: hex(64),
          openedAt: dateTime,
        }),
        Fill: object({
          fillId: hex(64),
          orderHash: hex(64),
          role: { type: "string", enum: ["TAKER", "MAKER"] },
          marketId: { type: "string" },
          side: { type: "string", enum: ["LONG", "SHORT"] },
          route: { type: "string", enum: ["DIRECT_BOOK", "PRIVATE_RFQ"] },
          requestedLots: { type: "integer" },
          filledLots: { type: "integer" },
          cancelledLots: { type: "integer" },
          price: { type: "number" },
          priceTicks: integerString,
          feesUsd: { type: "number" },
          feesMinor: integerString,
          positionId: hex(64),
          positionLive: { type: "boolean" },
          outcome: { type: "string", enum: ["OPENED", "CLOSED"] },
          closedPositionId: nullable(hex(64)),
          transactionHash: hex(64),
          createdAt: dateTime,
        }),
        Receipt: object({
          receiptId: hex(64),
          fillId: hex(64),
          orderHash: hex(64),
          transactionHash: hex(64),
          marketId: { type: "string" },
          packageCode: { type: "string" },
          side: { type: "string", enum: ["LONG", "SHORT"] },
          route: { type: "string", enum: ["DIRECT_BOOK", "PRIVATE_RFQ"] },
          routeLabel: { type: "string" },
          lots: { type: "integer" },
          requestedLots: { type: "integer" },
          filledLots: { type: "integer" },
          cancelledLots: { type: "integer" },
          price: { type: "number" },
          feesUsd: { type: "number" },
          realizedPnlUsd: nullable({ type: "number" }),
          collateralReleasedUsd: nullable({ type: "number" }),
          guarantee: { type: "string" },
          evidence: { type: "string", enum: ["ONCHAIN", "TESTNET", "MAINNET"] },
          createdAt: dateTime,
        }),
        Order: object({
          orderHash: hex(64),
          accountId: hex(64),
          signer: hex(40),
          marketId: { type: "string" },
          route: { type: "string", enum: ["DIRECT_BOOK", "PRIVATE_RFQ"] },
          side: { type: "string", enum: ["LONG", "SHORT"] },
          lots: { type: "integer" },
          filledLots: { type: "integer" },
          remainingLots: { type: "integer" },
          limitPrice: { type: "number" },
          priceTicks: integerString,
          timeInForce: { type: "string", enum: ["GTC", "GTD", "IOC", "FOK"] },
          postOnly: { type: "boolean" },
          state: { type: "string", enum: ["WORKING", "PARTIALLY_FILLED", "FILLED", "CANCELLED", "EXPIRED"] },
          statusCode: { type: "integer", description: "Raw OrderState status enum (1 open, 2 partially filled, 3 filled, 4 cancelled, 5 expired)." },
          deadline: dateTime,
          maxFeeUsd: { type: "number" },
          collateralReservationUsd: { type: "number" },
          riskAdmissionId: nullable(hex(64)),
          fillIds: { type: "array", items: hex(64) },
          receiptIds: { type: "array", items: hex(64) },
          createdAt: dateTime,
        }),
        SerializedPublicOrder: {
          type: "object",
          description: "PublicOrder with uint128/int128/uint64/uint256 fields as decimal strings.",
          properties: {
            signer: hex(40),
            accountId: hex(64),
            policyId: hex(64),
            policyContextHash: hex(64),
            actionId: hex(64),
            targetKind: { const: 1 },
            seriesId: hex(64),
            packageId: hex(64),
            targetVersion: { type: "integer" },
            side: { type: "integer", enum: [1, 2] },
            lots: integerString,
            priceTicks: integerString,
            timeInForce: { type: "integer", enum: [1, 2, 3, 4] },
            deadline: integerString,
            executionModeId: hex(64),
            feeScheduleId: hex(64),
            feeScheduleVersion: { type: "integer" },
            maxFeeMinor: integerString,
            recipient: hex(40),
            permittedExecutor: hex(40),
            nonce: integerString,
            salt: hex(64),
            allowPartialFills: { type: "boolean" },
            minimumFillLots: integerString,
            remainderPolicy: { type: "integer", enum: [1, 2] },
            postOnly: { type: "boolean" },
            reduceOnly: { type: "boolean" },
          },
        },
        PrepareOrderRequest: object(
          {
            signer: hex(40),
            marketId: { type: "string" },
            side: { type: "string", enum: ["LONG", "SHORT"] },
            lots: { type: "integer", minimum: 1 },
            limitPrice: { type: "number", description: "On the market's grid: (limitPrice - onchain.priceOffset) x onchain.priceScale must be a whole number of ticks." },
            timeInForce: { type: "string", enum: ["GTC", "GTD", "IOC", "FOK"], default: "GTC" },
            expiresAt: { ...dateTime, description: "Required for GTD. Capped at 240s after chain time." },
            postOnly: { type: "boolean", default: false },
            maxFeeUsd: { type: "number", minimum: 0, description: "Defaults to twice the taker fee on the full consideration." },
          },
          ["signer", "marketId", "side", "lots", "limitPrice"],
        ),
        TransactionRequest: object({
          step: {
            type: "string",
            enum: [
              "APPROVE_LOCK_OPERATOR",
              "BIND_RISK",
              "REGISTER_ORDER",
              "PLACE_ON_BOOK",
              "MATCH",
              "CANCEL_ORDER",
              "SYNC_BOOK",
              "AUTHORIZE_LIFECYCLE",
              "EXECUTE_LIFECYCLE",
              "REGISTER_RFQ",
              "OPEN_RFQ",
              "LOCK_SELECTION",
              "CONFIRM_CAPACITY",
              "AUTHORIZE_SUBMISSION",
              "SUBMIT_RFQ",
              "CANCEL_RFQ",
            ],
          },
          description: { type: "string" },
          chainId: { type: "integer" },
          from: hex(40),
          to: hex(40),
          data: hex(),
          value: { const: "0" },
        }),
        PreparedOrder: object({
          orderHash: hex(64),
          accountId: hex(64),
          marketId: { type: "string" },
          order: ref("SerializedPublicOrder"),
          typedData: object({
            domain: object({ name: { const: "Setryn" }, version: { const: "1" }, chainId: { type: "integer" }, verifyingContract: hex(40) }),
            types: object({ PublicOrder: { type: "array", items: object({ name: { type: "string" }, type: { type: "string" } }) } }),
            primaryType: { const: "PublicOrder" },
            message: ref("SerializedPublicOrder"),
          }),
          chainTime: dateTime,
          deadline: dateTime,
          submitWithinSeconds: { type: "integer" },
          preconditions: object({
            accountExists: { type: "boolean" },
            availableCollateralMinor: integerString,
            requiredCollateralMinor: integerString,
            sufficientCollateral: { type: "boolean" },
            lockOperatorsApproved: { type: "boolean" },
          }),
          requiredTransactions: { type: "array", items: ref("TransactionRequest") },
          next: { type: "string" },
        }),
        SubmitOrderRequest: object({ order: ref("SerializedPublicOrder"), signature: hex() }),
        SubmitOrderResult: object({
          orderHash: hex(64),
          accountId: hex(64),
          signer: hex(40),
          marketId: { type: "string" },
          status: { const: "RISK_RESERVED" },
          riskAdmissionId: hex(64),
          riskReservationTransaction: nullable(hex(64)),
          validUntil: dateTime,
          transactions: { type: "array", items: ref("TransactionRequest") },
          next: { type: "string" },
        }),
        LifecycleAction: object({
          kind: { const: 4 },
          actor: hex(40),
          actorAccountId: hex(64),
          policyContextHash: hex(64),
          inputsHash: hex(64),
          successorsHash: hex(64),
          collateralReplacementsHash: hex(64),
          participantSetHash: hex(64),
          consentsHash: hex(64),
          riskDomainId: hex(64),
          riskDomainVersion: { type: "integer" },
          feeScheduleId: hex(64),
          feeScheduleVersion: { type: "integer" },
          economicTransitionHash: hex(64),
          compressionPlanId: hex(64),
          breaksPackageProvenance: { type: "boolean" },
          packageBreakPermissionHash: hex(64),
          actorMaximumLiabilityIncreaseBaseUnits: integerString,
          actorMaximumCollateralIncreaseBaseUnits: integerString,
          inputCount: { type: "integer" },
          successorCount: { type: "integer" },
          participantCount: { type: "integer" },
          deadline: integerString,
          nonce: integerString,
          permittedExecutor: hex(40),
          salt: hex(64),
        }),
        LifecycleInput: object({
          positionId: hex(64),
          expectedImmutableHash: hex(64),
          expectedLifecycleHash: hex(64),
          expectedPositionLots: integerString,
          actionLots: integerString,
        }),
        LifecycleCollateralReplacement: object({ accountId: hex(64), collateralId: hex(64), terminalLiabilityBaseUnits: integerString }),
        LifecycleConsent: object({
          actionId: hex(64),
          accountId: hex(64),
          signer: hex(40),
          nonce: integerString,
          deadline: integerString,
          maximumLiabilityIncreaseBaseUnits: integerString,
          maximumCollateralIncreaseBaseUnits: integerString,
          allowsPackageBreak: { type: "boolean" },
          salt: hex(64),
        }),
        PrepareExitRequest: object({
          signer: hex(40),
          positionIds: { type: "array", items: hex(64), minItems: 2, maxItems: 2, description: "The open position and the opposite position that closes it." },
        }),
        PreparedExit: object({
          actionId: hex(64),
          accountId: hex(64),
          counterpartyAccountId: hex(64),
          positions: { type: "array", items: object({ positionId: hex(64), side: { type: "string", enum: ["LONG", "SHORT"] }, lots: { type: "integer" } }) },
          action: ref("LifecycleAction"),
          inputs: { type: "array", items: ref("LifecycleInput") },
          replacements: { type: "array", items: ref("LifecycleCollateralReplacement") },
          consent: ref("LifecycleConsent"),
          consentSignature: hex(),
          typedData: object({
            domain: object({ name: { const: "Setryn" }, version: { const: "1" }, chainId: { type: "integer" }, verifyingContract: hex(40) }),
            types: object({ SetrynLifecycleActionV1: { type: "array", items: object({ name: { type: "string" }, type: { type: "string" } }) } }),
            primaryType: { const: "SetrynLifecycleActionV1" },
            message: { type: "object", description: "The action fields plus chainId (decimal string) and engine (the SignedLifecycleEngine)." },
          }),
          chainTime: dateTime,
          deadline: dateTime,
          submitWithinSeconds: { type: "integer" },
          next: { type: "string" },
        }),
        SubmitExitRequest: object({
          action: ref("LifecycleAction"),
          inputs: { type: "array", items: ref("LifecycleInput") },
          replacements: { type: "array", items: ref("LifecycleCollateralReplacement") },
          consent: ref("LifecycleConsent"),
          consentSignature: hex(),
          actorSignature: hex(),
        }),
        SubmitExitResult: object({
          actionId: hex(64),
          accountId: hex(64),
          signer: hex(40),
          positionIds: { type: "array", items: hex(64) },
          validUntil: dateTime,
          transactions: { type: "array", items: ref("TransactionRequest") },
          next: { type: "string" },
        }),
        ...rfqSchemas(),
        IssueKeyRequest: object(
          {
            name: { type: "string", minLength: 1, maxLength: 64 },
            scopes: { type: "array", items: { type: "string", enum: ["read", "trade"] } },
            signers: { type: "array", items: hex(40), maxItems: 10 },
            rateLimit: object({ capacity: { type: "integer", minimum: 1, maximum: 200 }, refillPerSecond: { type: "number", exclusiveMinimum: 0, maximum: 50 } }),
          },
          ["name"],
        ),
        ApiKey: object({
          id: { type: "string" },
          name: { type: "string" },
          prefix: { type: "string" },
          scopes: { type: "array", items: { type: "string", enum: ["read", "trade"] } },
          signers: { type: "array", items: hex(40) },
          rateLimit: object({ capacity: { type: "integer" }, refillPerSecond: { type: "number" }, remaining: { type: "integer" }, resetSeconds: { type: "integer" } }),
          createdAt: dateTime,
          lastUsedAt: nullable(dateTime),
          revokedAt: nullable(dateTime),
          status: { type: "string", enum: ["ACTIVE", "REVOKED"] },
          usage: object({ requests: { type: "integer" }, errors: { type: "integer" }, rateLimited: { type: "integer" }, replayRejected: { type: "integer" } }),
          recentRequests: {
            type: "array",
            items: object(
              { id: { type: "string" }, at: dateTime, method: { type: "string" }, path: { type: "string" }, status: { type: "integer" }, durationMs: { type: "integer" }, code: { type: "string" } },
              ["id", "at", "method", "path", "status", "durationMs"],
            ),
          },
        }),
      },
    },
  });
}

const RFQ_STATES = [
  "INVITING",
  "COLLECTING",
  "SELECTION_LOCKED",
  "CAPACITY_RESERVED",
  "AUTHORIZED",
  "SUBMITTED",
  "CLEARING",
  "SETTLED",
  "CANCELLED",
  "EXPIRED",
  "REJECTED",
];

function rfqSchemas(): Record<string, Schema> {
  const typedData = (primaryType: string, message: string): Schema =>
    object({
      domain: object({ name: { const: "Setryn" }, version: { const: "1" }, chainId: { type: "integer" }, verifyingContract: hex(40) }),
      types: object({ [primaryType]: { type: "array", items: object({ name: { type: "string" }, type: { type: "string" } }) } }),
      primaryType: { const: primaryType },
      message: ref(message),
    });
  const quote = object({
    quoteId: hex(64),
    rfqId: hex(64),
    solver: { type: "string" },
    maker: hex(40),
    makerAccountId: hex(64),
    price: { type: "number", description: "The price the requester trades at: the ask for a LONG request, the bid for a SHORT request." },
    priceTicks: integerString,
    lots: { type: "integer" },
    remainingLots: { type: "integer" },
    maxFeeUsd: { type: "number" },
    maxFeeMinor: integerString,
    maximumLiabilityUsd: { type: "number" },
    withinLimit: { type: "boolean", description: "At or inside the requester's signed limit price. Only such a quote can be accepted." },
    state: { type: "string", enum: ["OFFERED", "RESERVED", "SELECTED", "CONSUMED", "CANCELLED", "EXPIRED", "REJECTED"] },
    statusCode: { type: "integer", description: "Raw MakerQuoteStatus enum." },
    expiresAt: dateTime,
    capacityExpiresAt: dateTime,
    offeredAt: dateTime,
  });
  return {
    RfqQuote: quote,
    Rfq: object({
      rfqId: hex(64),
      marketId: { type: "string" },
      seriesId: hex(64),
      accountId: hex(64),
      taker: hex(40),
      takerOrderHash: hex(64),
      side: { type: "string", enum: ["LONG", "SHORT"] },
      sidePolicy: { type: "string", enum: ["BUY_ONLY", "SELL_ONLY", "TWO_WAY"] },
      lots: { type: "integer" },
      filledLots: { type: "integer" },
      limitPrice: nullable({ type: "number" }),
      limitPriceTicks: nullable(integerString),
      timeInForce: nullable({ type: "string", enum: ["GTC", "GTD", "IOC", "FOK"] }),
      maxFeeUsd: { type: "number" },
      state: { type: "string", enum: RFQ_STATES, description: "Open states read EXPIRED once the chain clock passes the deadline." },
      statusCode: { type: "integer", description: "Raw RfqStatus enum." },
      selectedQuoteId: nullable(hex(64)),
      quotes: { type: "array", items: ref("RfqQuote") },
      fillIds: { type: "array", items: hex(64) },
      receiptIds: { type: "array", items: hex(64) },
      deadline: dateTime,
      createdAt: dateTime,
    }),
    SerializedRfqRequest: {
      type: "object",
      description: "PrivateRfqRequest with uint128/uint64/uint256 fields as decimal strings.",
      properties: {
        taker: hex(40),
        takerAccountId: hex(64),
        takerOrderHash: hex(64),
        targetKind: { const: 1 },
        seriesId: hex(64),
        packageId: hex(64),
        targetVersion: { type: "integer" },
        hasPackageLegCommitment: { type: "boolean" },
        packageLegsHash: hex(64),
        sidePolicy: { type: "integer", enum: [1, 2] },
        lots: integerString,
        allowPartialFills: { type: "boolean" },
        minimumFillLots: integerString,
        remainderPolicy: { type: "integer", enum: [1, 2] },
        feeScheduleId: hex(64),
        feeScheduleVersion: { type: "integer" },
        maxFeeMinor: integerString,
        riskDomainId: hex(64),
        riskDomainVersion: { type: "integer" },
        privacyModeId: hex(64),
        executionModeId: hex(64),
        disclosurePolicyHash: hex(64),
        eligibleMakerSetHash: hex(64),
        deadline: integerString,
        permittedExecutor: hex(40),
        nonce: integerString,
        salt: hex(64),
      },
    },
    SerializedRfqSelection: object({
      rfqId: hex(64),
      quoteId: hex(64),
      taker: hex(40),
      executor: hex(40),
      nonce: integerString,
      deadline: integerString,
      salt: hex(64),
    }),
    PrepareRfqRequest: object(
      {
        signer: hex(40),
        marketId: { type: "string" },
        side: { type: "string", enum: ["LONG", "SHORT"] },
        lots: { type: "integer", minimum: 1 },
        limitPrice: { type: "number", description: "Worst accepted price, on the market's grid." },
        timeInForce: { type: "string", enum: ["GTC", "GTD", "IOC"], default: "IOC" },
        expiresAt: { ...dateTime, description: "Required for GTD. Capped at 240s after chain time." },
        maxFeeUsd: { type: "number", minimum: 0, description: "Defaults to twice the taker fee on the full consideration." },
      },
      ["signer", "marketId", "side", "lots", "limitPrice"],
    ),
    PreparedRfq: object({
      rfqId: hex(64),
      orderHash: hex(64),
      accountId: hex(64),
      marketId: { type: "string" },
      order: ref("SerializedPublicOrder"),
      orderTypedData: typedData("PublicOrder", "SerializedPublicOrder"),
      request: ref("SerializedRfqRequest"),
      requestTypedData: typedData("PrivateRfqRequest", "SerializedRfqRequest"),
      chainTime: dateTime,
      deadline: dateTime,
      submitWithinSeconds: { type: "integer" },
      preconditions: object({
        accountExists: { type: "boolean" },
        availableCollateralMinor: integerString,
        requiredCollateralMinor: integerString,
        sufficientCollateral: { type: "boolean" },
        lockOperatorsApproved: { type: "boolean" },
      }),
      requiredTransactions: { type: "array", items: ref("TransactionRequest") },
      next: { type: "string" },
    }),
    SubmitRfqRequest: object({
      order: ref("SerializedPublicOrder"),
      orderSignature: hex(),
      request: ref("SerializedRfqRequest"),
      requestSignature: hex(),
    }),
    SubmitRfqResult: object({
      rfqId: hex(64),
      orderHash: hex(64),
      accountId: hex(64),
      signer: hex(40),
      marketId: { type: "string" },
      status: { const: "RISK_RESERVED" },
      riskAdmissionId: hex(64),
      riskReservationTransaction: nullable(hex(64)),
      validUntil: dateTime,
      transactions: { type: "array", items: ref("TransactionRequest") },
      next: { type: "string" },
    }),
    SolicitQuotesResult: object({
      rfqId: hex(64),
      solicited: { type: "array", items: object({ solver: { type: "string" }, quoteId: hex(64) }) },
      quotes: { type: "array", items: ref("RfqQuote") },
    }),
    PreparedRfqAcceptance: object({
      rfqId: hex(64),
      quoteId: hex(64),
      quote: ref("RfqQuote"),
      selection: ref("SerializedRfqSelection"),
      typedData: typedData("RfqSelectionAuthorization", "SerializedRfqSelection"),
      chainTime: dateTime,
      deadline: dateTime,
      submitWithinSeconds: { type: "integer" },
      next: { type: "string" },
    }),
    AcceptRfqResult: object({
      rfqId: hex(64),
      quoteId: hex(64),
      signer: hex(40),
      price: { type: "number" },
      priceTicks: integerString,
      lots: { type: "integer" },
      validUntil: dateTime,
      transactions: { type: "array", items: ref("TransactionRequest") },
      next: { type: "string" },
    }),
    RfqSettlement: object({
      rfqId: hex(64),
      marketId: { type: "string" },
      state: { type: "string", enum: RFQ_STATES },
      quoteId: nullable(hex(64)),
      fillId: nullable(hex(64)),
      receiptId: nullable(hex(64)),
      positionId: nullable(hex(64)),
      transactionHash: nullable(hex(64)),
      filledLots: { type: "integer" },
      price: nullable({ type: "number" }),
      priceTicks: nullable(integerString),
      feesUsd: nullable({ type: "number" }),
      feesMinor: nullable(integerString),
      route: { const: "PRIVATE_RFQ" },
      guarantee: { type: "string" },
      next: { type: "string" },
    }),
  };
}
